### ISSUE TITLE
Generic metadata support

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1195]
Motivation
----------

Currently, we only have a fixed set of metadata that is principally exposed via the core/meta.py, api/meta.py, client/metaclient.py modules. These metadata are strictly enforced based on the schema of the DID and require a schema-change for every new metadata field.

This task is to support the use of arbitrary key:value pairs per DID based on JSON.

Modification
------------
1. [x] re-enable and redo test/test_meta.py to conform to a new generic metadata interface
2. [x] adapt client/metaclient.py and bin/rucio to use the new metadata interface
3. [x] then, either, create new metadata table with three principal columns "scope", "name", "json metadata", or extend _did_ table with "json metadata" column (to be decided)
4. [x] adapt api/meta.py and core/meta.py to use the new schema

**Comment by asketagarwal** [comment]
I'll be taking this up

**Comment by tbeerman** [comment]
I'm currently still having troubles getting Oracle 12c reliably running on travis, i.e., you will need to add a switch in the code to enable and disable this feature based on the version of Oracle. So if the version is < 12 then disable json support otherwise enable it. This will be necessary anyway since our production DB is still 11g and we also would run tests both against 11g and 12c.
