### ISSUE TITLE
rucio mover should correctly set trace parameters

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#1214]
Motivation
----------
The rucio mover does not correctly send traces by not reporting the actual usrdn, pandaid, etc.

Modification
------------
Use the CLI parameters provided by the rucio clients:
`--trace_appid, --trace_dataset, --trace_datasetscope, --trace_eventtype, --trace_pq, --trace_taskid, --trace_usrdn`

**Comment by TomasJavurek** [comment]
The wrong traces were sent by download() method in downloadclient, that is going to be deprecated: https://github.com/rucio/rucio/issues/1378
the other method download_dids(), should send the traces correctly. Only missing piece is to add correct format to method download_pfns(), where the traces are not introduced at all. This is not problem for now, because pilot is sending traces alone (the switcher that distinguish between copytools is not active). The possibility of propagating the trace created by pilot to the rucio clients is being discussed.

**Comment by bari12** [comment]
Pilot1 Done; Pilot2 still missing

**Comment by bari12** [comment]
Any update?
