### ISSUE TITLE
Call list_replicas in downloadclient only once

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1427]
Motivation
----------
Right now `list_replicas` is called in a loop for every did. In cases where the pilot runs over N=15 files this creates a lot of calls on the server. This should be changed to just one `list_replicas` bulk call.

The reason why this is done is that the did could potentially be a dataset, and right now, if the call is made in bulk the association between resolved files and dataset gets lost. However, this association is needed for the traces. The idea would be to expand the list_replicas result with the used did. This requires changes in the client and the core.

- [x] Adapt list_replicas to include the dataset/container name in the result
- [x] Adapt the downloadclient to list replicas in bulk

**Comment by TWAtGH** [comment]
Another problem with this is that the download API is currently designed to allow to specify parameters per DID (e.g. rse-expression, schemes, resolve_archives), while list_replicas takes those arguments per call.
Solutions are:
1. Merge the DIDs by the parameters to reduce the list_replicas calls to a minimum
2. Create a new method in the API that is more strict in specifying the parameters but fits to list_replicas
3. Drop the support of specifying parameters per DID in the current download API
4. Change list_replicas so that it is possible to specify parameters per DID

**Comment by mlassnig** [comment]
Change for list_replicas():

Return (multiple) fields in metalink: `<parent>...did...</parent>`

Return single list field in json: `'parents': [did1, did2, ...]`

Convention is not to resolve all parents, only the ones the user is requesting.
