### ISSUE TITLE
Add downloadclient and uploadclient to main Client object

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1470]
Motivation
----------
Add the two clients to the main client object
https://github.com/rucio/rucio/blob/master/lib/rucio/client/client.py#L24

**Comment by bari12** [comment]
@TWAtGH during the creation of the PR we saw that UploadClient and DownloadClient are not inherited from BaseClient. Is there a special reason for this?

**Comment by TWAtGH** [comment]
I don't really remember to be honest. But looking at it now the download and upload client don't really fit into the api like the other classes do. The two classes only need to use the client and don't do rest calls themselves. 
I guess that were my thoughts when creating these classes. I probably wasn't aware of how the client object is meant to be used.
However changing this now will be a little bit challenging since the `__init__` calls are getting some custom parameters and should be downward compatible.

**Comment by TWAtGH** [comment]
I would suggest to close this one. As I've written above adding these classes to the main client is not necessary and could be quite problematic
