### ISSUE TITLE
Searching for a DID shows "Could not find the DID" but did was found

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1619]
Motivation
----------
See https://its.cern.ch/jira/browse/RUCIO-2883

**Comment by hahahannes** [comment]
It seems that the request to:
```
https://rucio-ui.cern.ch/proxy/dids/data18_13TeV/data18_13TeV.00362204.physics_BphysLS.recon.AOD.k988_tid15553683_00/did_meta
``` 
fails because of [a broken check for the oracle version](https://github.com/rucio/rucio/blob/master/lib/rucio/core/did.py#L1291) (should be session.connection() instead session.connection). I think it is not usable at the moment because of the missing oracle upgrade. So I would change the error message to a more meaningful like 'Could not retrieve DID meta informations' in case this request fails, but it would be still shown on top of the page.

**Comment by bari12** [comment]
get_did_meta should never be called at the moment (It needs the oracle version upgrade). I strongly suspect that we should call `../meta` here like in all other cases. I think this was changed as an error.

The connection() is a different bug and should be fixed, can you please create a ticket for this?

**Comment by hahahannes** [comment]
Okay, linking the ticket for the connection bug [here](https://github.com/rucio/rucio/issues/1639).
