### ISSUE TITLE
Undertaker crash when a DID is attach/detached many times

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1772]
Motivation
----------
The undertaker crash when a DID is attach/detached many times. The problem is due to the archival in the history table : https://github.com/rucio/rucio/blame/master/lib/rucio/core/did.py#L714 .

**Comment by bari12** [comment]
Just on a side-note: The way we manage the PKs for history tables in the models.py is wrong.
For Oracle we do not create PKs, only in the models.py we create them, but as new experiments create their tables with the models.py install script, it should be handled differently.

**Comment by vingar** [comment]
I think it's historical because sqlalchemy enforces the definition of PK on table, otherwise it fails. This explains why PKs are defined in models but not in Oracle.

**Comment by bari12** [comment]
Yes, sqlalchemy expects a primary Key, otherwise the whole mapping from rows to addressable objects does not make sense.
What is a little bit better is to define a fake PK, like in the replication rule history table. With a history_id as PK (Which does not get created in Oracle) - but this is still kind of wrong for experiments which create their schema from models.py, because they will still end up with a PK. - But thats more of a long-term change.
In this specific case, the merge just doesnt work because merging on a table without a PK doesnt make much sense.

**Comment by vingar** [comment]
yes in that case the merge is wrong.

**Comment by bari12** [comment]
Fixing this with a PR now, more for the other tables in #1818
