### ISSUE TITLE
REST call for requests is broken by '/' in DIDs

### ISSUE THREAD

**Issue by dciangot** [rucio/rucio#1791]
Motivation
----------
As discussed in #1786 , the REST call of https://github.com/rucio/rucio/blob/master/lib/rucio/web/rest/webpy/v1/request.py get broken for DIDs containing `/`

Modification
------------
I think that rather than doing this (*) we can pass all the needed information (scope, name, rse) as params instead of including them in the url path. 

(*) https://github.com/rucio/rucio/blob/master/lib/rucio/web/rest/webpy/v1/request.py#L38

**Comment by bari12** [comment]
In https://github.com/rucio/rucio/blob/master/lib/rucio/web/rest/webpy/v1/did.py we did this with the SCOPE_NAME_REGEXP 
There is an issue with this way though (see #1746) but in this case it should be fine.
I think just submitting these as params is not a bad idea, but due to backward compatibility I would go the regexp way.

**Comment by dciangot** [comment]
Ok, thanks, I missed the SCOPE_NAME_REGEXP thing. I'll go with that then.
