### ISSUE TITLE
Move cmstfc.py into core Rucio code

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#1803]
Motivation
----------

Right now we have our python file which describes our LFN to PFN algorithm in our own repo: https://github.com/dmwm/CMSRucio/blob/master/docker/CMSRucioClient/scripts/cmstfc_lfn2pfn.py

This has the unfortunate side effect of requiring CMS to build it's own docker container. I'd like to move this into Rucio either at  rucio/lib/rucio/common/schema/ where another policy file is or at rucio/lib/rucio/rse/protocols/ which is where the code that imports it lives. @sartiran, I think to import this we can just specify the full python path in the config file and all is good.

Modification
------------

Once we have agreement on whether to do this and where to put it, we just move the CMS file over.

**Comment by bari12** [comment]
In the medium term the plan was to get these VO specific modules (schema, policy, permissions, lfn2pfn algorithms) out of the core package. We discussed this some time ago and we want to offer two different ways to do that. It's summarized it in #533 
If you can wait for that ticket to make progress, I would just leave it like this, otherwise I would suggest we move it to `rucio/lib/rucio/common/schema/` until we make progress with #533

**Comment by ericvaandering** [comment]
I think I'd like to get into schema while we wait for #533. This avoids us having to build our own containers and chase versions. It would allow us to just use rucio/containers. Maybe we can get a CMS person to look into #533.
