### ISSUE TITLE
Improve reaper scalability

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1885]
Motivation
----------
The way the reaper is implemented now leads to the fact that we have different instances processing each a fixed partition. In the worst case scenario, one can have one reaper dedicated to one RSE that will have millions of files to process, whereas all the other instances stay idle because there is nothing to be deleted on the RSEs they serve. Here is a proposition to have a horizontally scalable reaper.

Modification
------------
The proposal is to split the reaper into 2 parts.

- One first daemon `reaper-preparer` would run the `list_unlocked_replicas` on all the RSEs and identify all the replicas that need to be deleted based on the `needed_free_space`. All these replicas would get the state `BEING_DELETED`.
- A second daemon (the true reaper) which will run the physical deletion gets the list of all `BEING_DELETED` replicas. The query can be partitioned on a hash of the name of the DIDs to have balanced partitions between different instances. Doing this way, we can ensure that all instances will get the same share of work. The true reaper physically deletes the files and issue the `delete_replicas`.

There might be a few issues to address (e.g. it can be that all the reapers are running against the same RSE and can cause some denial of service).
Comments welcome.

**Comment by bari12** [comment]
I don't think we need the reaper-preparer. I mean the key difference here is that the main reaper does the partitioning different, on hash of dids and not RSEs. But it would work exactly the same if the selection happens on the expired replicas, instead of the ones marked as `BEING_DELETED` by the preparer.

The thing we have to get right here is not to overload an RSE. We probably would need some kind of cross-communication of the reapers here. Another thing where we have to be careful (It's probably fine, but just raising the point) is the whole "remove the dataset once the last replica is deleted" workflows, as there might be race conditions if different reapers delete on the same RSE.

**Comment by cserf** [comment]
The problem if you hash on DIDs is that it can be you can get millions of files on the top of the queue on the same RSE. In that case, there will be no deletion on the other RSEs and one can quickly go into trouble. What I propose is to build a list of replicas to delete where each RSE gets a share (e.g. it can be `needed_free_space`). It would be something like :
```
rep_to_delete = []
tot_share = sum of all needed_free_space on all rses
for rse in rses:
    get a list of unlocked replicas on rse
    take needed_free_space/tot_share replicas from the previous list and insert into rep_to_delete
return rep_to_delete
```
Of course, all of this can be done in `list_unlocked_replicas`, but that makes this method a bit complicated, that's why I was thinking about a new daemon.

**Comment by cserf** [comment]
Another proposal was chosen
