### ISSUE TITLE
Fix pylint tests on travis

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#209]
Motivation
----------

The current command to get the list of changed files for a PR, which was originally taken from the old build bot script, does not work with the travis workflow and has to be fixed.

Modification
------------

Expected behavior
-----------------

**Comment by vingar** [comment]
Having a simple test on all files to check that we don't have pylint errors would be good as well. 
I quickly googled travis+pylint and few options exists apparently in travis but I didn't have time to investigate more. Something to look ?

**Comment by tbeerman** [comment]
Running it over all files can be enabled easily, will just take a bit longer.

**Comment by bari12** [comment]
There is two things: For the errors, testing everything is fine, because there really should not be any error in the code. Testing for score though you should do file by file. If you get a score for everything, the few files changed in the PR will not really move the general score, although the files themselves might have a very bad one.
