### ISSUE TITLE
Updating replicas state

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#2433]
Motivation
----------
from rucio.client import Client
rucio_client = Client()
filename = 'test_2019-04-03.txt'
scope = 'user.ddmadin'
rsename = 'UNI-FREIBURG_DATADISK'
rucio_client.update_replicas_states(rsename, [{'scope':scope, 'name':filename}])

returns:

rucio.common.exception.RucioException: An unknown exception occurred.
Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97'))

but the site is ok and I can download the replica using gfal. 

Modification
------------

**Comment by TomasJavurek** [comment]
with defining a state:
[root@rucio-nagios-prod-02 grid_testing]# python update_state_bug.py
Traceback (most recent call last):
 File "update_state_bug.py", line 7, in <module>
   rucio_client.update_replicas_states(rsename, [{'scope':scope, 'name':filename, 'state':'A'}])
 File "/usr/lib/python2.7/site-packages/rucio/client/replicaclient.py", line 238, in update_replicas_states
   raise exc_cls(exc_msg)
rucio.common.exception.UnsupportedOperation: The resource doesn't support the requested operation.
Details: State AVAILABLE for replica user.ddmadin:test_2019-04-03.txt on UNI-FREIBURG_DATADISK cannot be updated
but right this gives different error message

**Comment by bari12** [comment]
Is it possible that this replica was already in state `A`?

**Comment by TomasJavurek** [comment]
hmmm, my bug, as usual. Scope is wrong. But still, the exception should be turned to something more understandable. Like, did doesn't exist or so.

**Comment by bari12** [comment]
It's an optimisation of queries here. We don't check if the DID exists, we just execute an UPDATE query and check if it affected a row. If not, the error is raised. (Which could be: replica was already in that state, replica is in a state which should not be changed, replica does not exist etc.) It's difficult to give a specific error here without additional queries.
I am not sure if we should change that, since this is also not really a command a simple user is exposed to.
