### ISSUE TITLE
list_replicas returns a generator with an empty string when there are no replicas

### ISSUE THREAD

**Issue by sartiran** [rucio/rucio#2517]
Motivation
----------
The list_replica command when no replicas are there matching the requirements, returns a generator with 1 element which is an empty string
```  
>>> list(rcli.list_replicas([{'name': '/ST_t-channel_top_4f_InclusiveDecays_TuneCP5_PSweights_13TeV-powheg-pythia8/RunIIFall17DRPremix-PU2017_94X_mc2017_realistic_v11-v1/AODSIM#6f7f91ba-4c38-4a31-af33-aa99287a9839', 'scope': 'cms'}], rse_expression='T2_FR_GRIF_IRFU'))
[u'']
```

I may be wrong but I think it used to return an empty generator in previous versions (current 1.19.7)

Modification
------------
return an empty list

**Comment by bziemons** [comment]
@bari12 #4000 actually fixes this by always setting the HTTP Content-Type again. The bug was introduced in f6bd99332deb10fd877fbc10cd632e6656729379

However I would suggest checking the response in `baseclient._load_json_data` before returning it here:
https://github.com/rucio/rucio/blob/f6d37c6cc340c0779fe5a77d96483043ef421b60/lib/rucio/client/baseclient.py#L349

I will prepare a PR for this. See #4002
