### ISSUE TITLE
Separate third_party_copy activity into read and write

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#2592]
Motivation
----------
Separate the `third_party_copy` activity into a `third_party_copy_read` and `third_party_copy_write` activity. Also possivle is to use Read WAN for the source. Needs discussion

**Comment by vokac** [comment]
You still call new configuration third party read/write and I'm not completely sure what exactly does this mean. For XRootD it is necessary that destination endpoint supports TPC, because only pull mode is available, but for WebDAV you can either contact destination endpoint and use pull mode or it is also fine if you contact source endpoint and use push mode. Currently FTS use for WebDAV pull mode first and than automatically fallback to push (it is possible to configure FTS not to try push) ... this makes things even more interesting in case of multisource transfers and I have no idea how FTS currently deals with such TPC transfers in case of push fallback. I guess new third party read/write configuration doesn't try to cover all possible scenarios (push model).
