### ISSUE TITLE
Rucio Should Raise an Exception if No Caching is Available

### ISSUE THREAD

**Issue by bjwhite-fnal** [rucio/rucio#2822]
Motivation
----------
In the case where no backend cache is available either locally or remote for Dogpile to communicate with, Dogpile will return NO_VALUE, masking the true "connection refused" error due to no process actually listening at the given endpoint.

Modification
------------
Raise an exception or provide a warning when there is no caching service available at the configured endpoint provided to Dogpile.

**Comment by bjwhite-fnal** [comment]
The thought we had was that we could set and get a value in the cache with the Dogpile interface to evaluate the status of the caching system when the regions are created. However, we were not sure where in the codebase to place such functionality. I was thinking in core/, but there is not an obvious core module for placement of such a utility.

**Comment by mlassnig** [comment]
Maybe `lib/rucio/common/utils.py` is a good place, it has a couple other dogpile related functions in there already.

**Comment by bari12** [comment]
In principle I think raising a warning is a good idea, so that there is at least a trace for this, but this might spam the log quite a bit. We always considered the caching backends as something optional, so we should not spam the users who decide not to run any. 
Make the caching part of rucio.cfg, so we can track this caching decision? See #2812 ?
