### ISSUE TITLE
delete_rule for rule_deleters does not work

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#2886]
Motivation
----------

The conversion of issuer into an object is not done (at least) for the delete_replication_rule :
```
def delete_replication_rule(rule_id, purge_replicas, issuer):
    """
    Deletes a replication rule and all associated locks.

    :param rule_id:  The id of the rule to be deleted
    :param issuer:   The issuing account of this operation
    :raises:         RuleNotFound, AccessDenied
    """
    kwargs = {'rule_id': rule_id, 'purge_replicas': purge_replicas}
    if not has_permission(issuer=issuer, action='del_rule', kwargs=kwargs):
        raise AccessDenied('Account %s can not remove this replication rule.' % (issuer))
    rule.delete_rule(rule_id=rule_id, purge_replicas=purge_replicas, soft=True)
```
It leads to a permission issue when trying to delete a rule.
The other methods need to be checked too

**Comment by bari12** [comment]
The conversion is done in the permission API, this is correct. The problem here is that sometimes we do comparisons such as:
`if issuer in rse_attr.get('rule_deleters').split(','):`
Which does not work, since the issuer object is looked for in a list of strings. This needs to be adapted to `issuer.external`.
See https://github.com/rucio/rucio/blob/525812b8f83f1069d38ab78aebedb732f21e77ec/lib/rucio/core/permission/atlas.py#L473
There might be other places in the permission code which do that as well.

**Comment by bari12** [comment]
@hahahannes Can you please have a look in the permission APIs and adapt these lines? (Wherever issuer `in` is used. Thanks!
