### ISSUE TITLE
Custom traces compatible with the bulk option.

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#3101]
Motivation
----------
As of today, one can pass a reference to a list where the traces from Rucio can be uploaded. If the other party already provided some traces, we have no way to update them so far, they would need to update the traces according to the information we provided. There is an option for trace_pattern that can be used for traces that Rucio is producing, but thah seems to be an option only for a single trace.

Modification
------------
This is matter of discussion. Either the other party provides list of references that they created and Rucio just updates them, or Rucio send a traces and the other party merges them with the parts of traces coming from Rucio.

**Comment by TWAtGH** [comment]
That is because traces were not meant to be used as return values for some time. They were just the data for the monitoring system. Actually I don't like that we start to expand this even more.
Some time ago I discussed another approach with @bari12 were it would be possible to set callback functions for different steps of the download client. E.g., one for failed downloads, one for successful downloads, one for failed attemps...
For each event the download client would call this function and give the user the opportunity to react to the event.

**Comment by bari12** [comment]
This needs some more discussion next week. I am not sure if the callbacks alone solves this well enough.

**Comment by TomasJavurek** [comment]
In meanwhile, we discussed with Tobi whether current downloadclient is threadsafe or not. The problem is in the list reference that I created in pilot for adding the traces:
https://github.com/rucio/rucio/blob/master/lib/rucio/client/downloadclient.py#L454

According to the following article about locking:
http://effbot.org/zone/thread-synchronization.htm

appending to a list is threadsafe operation.
