### ISSUE TITLE
SAML Authentication wrongly requires client config section

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#3209]
PR # 2689 causes a regression crash in the server by requiring a [client] section in the config file for the server. 

Should use the no-exception parameter, right?

**Comment by bari12** [comment]
Could be fixed with the no-exception parameter. But to check the client config in a pure server functionality is already wrong. As you said, the client config should not be necessary on a server. I think the right change is to do this similar to other optional (extras) modules. Check if they are on path, and only load them then.
Similar to https://github.com/rucio/rucio/blob/7e32dee2c3af1fd51417481483449ca3d9c3bf28/lib/rucio/client/baseclient.py#L67

**Comment by Ruturaj123** [comment]
I am working on the issue. Just wanted to ask what should be done here:
https://github.com/rucio/rucio/blob/870d36024db27f709d66e9b7c12974bf0edc6fe2/lib/rucio/web/rest/webpy/v1/authentication.py#L539
Does this need to be changed too?

**Comment by bari12** [comment]
Hi Ruturaj, no this one is fine. The server does also use the rucio config file. It just should not be assumed that there is a `[client]` section in the server config. This is somewhat contradictive.
