### ISSUE TITLE
StoRM protocol logging, exceptions and getting etag

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#3285]
Motivation
----------
Follow up of issue:
https://github.com/rucio/rucio/issues/3262

Modification
------------
- verification of reliability of the etag retrieval with rquests and davix.
- implementation of more reliable solution
- adding logging at the protocol level
- propagating the command to the pilot log

**Comment by vokac** [comment]
In case file doesn't exist davix-http still returns 0 as exit code while returned data contains just HTML code with 404 error, e.g.
```
[vokac@ui1 ~]$ davix-http --capath /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/etc/grid-security-emi/certificates --cert $X509_USER_PROXY -X PROPFIND davs://gridhttps-storm-atlas.cr.cnaf.infn.it:8443/webdav/atlas/atlasscratchdisk/rucio/user/mphipps/36/a1/missing_file.txt
<html><body><h1>/atlas/atlasscratchdisk/rucio/user/mphipps/36/a1/missing_file.txt Not Found (404)</h1></body></html>
(Davix::HttpRequest) Error: HTTP 404 : File not found 
[vokac@ui1 ~]$ echo $?
0
```
Even though stdout is most probably valid XML (last line comes from stderr) even latest code just fails a bit later with Exception (ExpatError?), because you are trying to access "d:getetag" element that doesn't really exists in a query for non-existent file. Exception should be clear and davix-http is not optimal interface.

I also think ATLAS capath should not be hardcoded in Rucio sources.
