### ISSUE TITLE
RSE distance APIs not exposed

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#330]
It seems that the only way to set distances between two RSEs is to directly manipulate the database (or write a python script that can execute against Rucio's DB).

I would expect this to be exposed via:
- the typical REST API,
- Python client API (perhaps requiring a new permission to be created?),
- `rucio-admin` CLI.

**Comment by bbockelm** [comment]
An example of where this is useful is a hosted Rucio instance where the VO may only interact via the REST API: the existing `rucio.core.distance` module wouldn't be usable in this case.

**Comment by vingar** [comment]
Proposed specification for the REST API:

Resource: /rses/distances/{source}/{destination} 
Operations: POST / DELETE / PUT / GET/

**Comment by bbockelm** [comment]
That API looks good to me!

How hard is it to implement?  Is there a similar REST API I can look at?

**Comment by bari12** [comment]
Yes,

The method path is always core <- api <- rest <- (network) <- client. So to make the rest api, you will have to implement the api as well. But all these are very simple and analogous. The api is basically the layer in between where permissions etc. are checked, in the core itself everything works without permissions.

I think a good stack to look at are the identities (Each account has different identities, such as username/pass, x509 certs, etc.)
So the API file is: https://github.com/rucio/rucio/blob/master/lib/rucio/api/identity.py
The REST interface is: https://github.com/rucio/rucio/blob/master/lib/rucio/web/rest/identity.py

You will also have to add the new apache endpoint to https://github.com/rucio/rucio/blob/master/etc/web/aliases-py26.conf and https://github.com/rucio/rucio/blob/master/etc/web/aliases-py27.conf so that apache/mod_wsgi can find it.
