### ISSUE TITLE
Allow registration of "lan" replicas

### ISSUE THREAD

**Issue by davidgcameron** [rucio/rucio#3312]
Motivation
----------

If the pilot uses the 'write_lan' activity to upload a file, it will send the corresponding pfn (usually an internal proxy) to panda which will then fail to add the replica in Rucio because it doesn't match the expected pfn. This is because the checks in add_replica are hard-coded to use the 'wan' domain:

https://github.com/rucio/rucio/blob/master/lib/rucio/core/replica.py#L1301

Modification
------------

The checks should be changed to allow adding replicas with 'lan' domain.

**Comment by TomasJavurek** [comment]
I implemented that just in procedural style. I am thinking about something nicer. The build-blocks are:
1) We don't want to call protocols, if wan pfns already worked.
2) We check lan pfns, but registration should still be done with wan_pfns.
3) We raise an exception if nore wan neither lan pfns fit.

**Comment by hseverini** [comment]
Hmm,

why is this working correctly at OU_OSCER_ATLAS then? Here, we also have a wan_pfn that's different from the lan_pfn: root://se1.oscer.ou.edu/ (the external xrootd proxy / SE) vs. root://dms.oscer.ou.edu/ (the internal xrootd redirector). And as far as I can tell, write_lan works fine here and uses the internal one. Or am I misunderstanding the issue here?

I very occasionally see a failed panda job with an error related to rucio not understanding root://dms.oscer.ou.edu/, but those are very infrequent.

Thanks,
    Horst

**Comment by davidgcameron** [comment]
I checked one job log and it looks like writes are using the write_wan host (se1)

https://aipanda184.cern.ch/condor_logs_2/20-03-04_06/grid.5156402.2.out

`2020-03-04 08:21:38,760 | INFO     | copytool_out        | gfal2                            | __gfal2_copy              | Event triggered: BOTH GFAL2:CORE:COPY LIST:ITEM file:///lscratch/31463202/atlas_djH56XPj/PanDA_Pilot-4661486006/HITS.20093197._121470.pool.root.1 => root://se1.oscer.ou.edu:1094//xrd/atlasdatadisk/rucio/mc16_13TeV/33/18/HITS.20093197._121470.pool.root.1.rucio.upload`

I don't know why they don't use the internal redirector. SITE_NAME is set correctly. But I think if they were using the internal redirector you would suffer the same problem.

**Comment by hseverini** [comment]
Thanks David.

I could've sworn we had this working correctly after Mario and Martin helped me with that last year some time, but maybe I'm just not remembering this correctly.

But we should get this working properly and automagically at any rate, since it will greatly improve our bandwidth, since using the internal redirector we basically have 70 Gbps to work with (7 storage servers), while anything that goes through the proxy is currently limited to its 10 Gbps 'through-flow'.

Thanks,
    Horst
