### ISSUE TITLE
Pip creation for WebUI mixing versions?

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#3435]
Motivation
----------

See https://github.com/rucio/containers/issues/65 The UI containers have inconsistent versions of webui and Rucio. Without much exploration, this looks to me like pip install webui is pulling the latest version of Rucio, not the matching one.

Modification
------------

**Comment by bari12** [comment]
I think this is a bit specific to the containers. On the puppet installations we always rely on having the core package installed in parallel to the machine, which is the one being used by the webui.

In the container, I think the core package is pulled in, in addition and not necessarily corresponding to the rucio webui version. Need to check if this is due to the setup.py of the webui package or the container creation process. @tbeerman ?

**Comment by bari12** [comment]
@tbeerman I think it should be fine to remove the Rucio main dependency in the setup.py of the webui?
https://github.com/rucio/rucio/blob/2a14c8984eecd1d702abaec0b8e0c9b96996bf4d/setup_webui.py#L100
Will this have any sideeffect on the container?

**Comment by ericvaandering** [comment]
I've added a PR to Rucio containers that should solve this. Want to close it here?

**Comment by ericvaandering** [comment]
PR merged
