### ISSUE TITLE
Configurable rse selection algorithm

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#3445]
Motivation
-----------
Selection method for the dst rses of whichever functionality of rucio could be configurable. 
For time being, just architectural proposal that will be stored close to transmogrifier.

Modification
------------

**Comment by bari12** [comment]
Just a few notes:
The PR Cedric made is now merged, so we should build on top of this:
- The RSE selection algorithm management should be similar to the lfn2pfn algorithm (Registration etc) so that we can manage them similarily in the VO configs
- Right now, the `select_algorithm` method specifies, that this is just done for chained subscriptions we should be more generic than that though, since it is thinkable that this is also done for non chained subscriptions.
- Right now the algorithm returns a list of RSEs. I think we should foresee that it can return either a list of rses OR also an RSE expression
- Right now split_mode is not possible for rules where the selection algorithm is used, I think it should be possible (Why not?)
