### ISSUE TITLE
Convert necromancer query to sqlalchemy native query

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#3563]
Motivation
----------
The necromancer uses the query https://github.com/rucio/rucio/blob/63c2659afe5cd01909ab783d7fa37ff1c2bff5d8/lib/rucio/core/replica.py#L466 which, for oracle, has a hardcoded part with `DEFAULT_SCHEMA_NAME` which is not used anywhere else. This requires to specify the `schema` specifically in the rucio.cfg, which for all other methods can be done natively from the DB connection string.

Modification
------------
It would be better to transform this query to an SQLAlchemy native query, similar to eg https://github.com/rucio/rucio/blob/63c2659afe5cd01909ab783d7fa37ff1c2bff5d8/lib/rucio/core/replica.py#L1847

That way we can also completely get rid of the `DEFAULT_SCHEMA_NAME` part.

**Comment by ericvaandering** [comment]
Might be possible to get rid of the config variable completely.

**Comment by TomasJavurek** [comment]
After a day of investigation, it is not possilbe, due to:
_The filter(text...)) is needed otherwise, SQLA uses bind variables and the index is not used._

I tested a possilbe replacement of the filter(text ...) line with:

`            filter(case([(models.RSEFileAssociation.state != ReplicaState.AVAILABLE,
                         models.RSEFileAssociation.rse_id)]) != None) .\`

and it sufferred from insane slowness wrt the original querry. I haven't find a way to force the index to be used. The `with_hint` method serves really only as a hint which index to use, but when using the sqlalchemy `case` method, the index is evidently ignorred.
