### ISSUE TITLE
Rucio upload does not honour write_lan

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#3626]
Motivation
----------

Even with `SITE_NAME` or a similar environmental variable set, the Rucio client does not propagate the domain correctly and `write_wan` is used instead of `write_lan`.

This is supposed to be addressed with the RSE Manager rewrite in issue #3147, but it is a high-priority item and should be fixed as soon as possible.

Modification
------------

Add some basic logging in order to be able to better identify which destination is used. Propagate the domain when calling `create_protocol()` in the RSE Manager.

**Comment by davidgcameron** [comment]
Can you give an example of when it doesn't work? When I tested it myself it worked ok. This part of the upload client should make sure lan domain is used:
https://github.com/rucio/rucio/blob/master/lib/rucio/client/uploadclient.py#L205

**Comment by davidgcameron** [comment]
Also, +1 for more logging. I had to put print() statements in the RSE manager and protocols to see what was going on because there isn't even a logger object there.

**Comment by dchristidis** [comment]
This sets `domain =  'lan'`. But, from my observations while investigating, the call to `upload()` a few lines below is not affected.

**Comment by davidgcameron** [comment]
Ok, I see it now, the domain is not set in `create_protocol()`. I guess my tests with Glasgow worked because write_wan was also set to the internal proxy.

**Comment by vokac** [comment]
I made tests with DESY-HH where everything seems to work fine, but it is just because of force_protocol that is passed to upload function. With different scheme set for preferred write_lan/0 vs. write_wan/0 transfers are done differently for LAN vs. WAN.

Basically it is just necessary to make upload call a bit more ugly with additional "force_domain" parameter and add domain parameters in these places
https://github.com/rucio/rucio/blob/2a1d8c41debcebc0ad2fa8f1ef7f44519767f2f2/lib/rucio/client/uploadclient.py#L236-L244
https://github.com/rucio/rucio/blob/2a1d8c41debcebc0ad2fa8f1ef7f44519767f2f2/lib/rucio/rse/rsemanager.py#L279
https://github.com/rucio/rucio/blob/2a1d8c41debcebc0ad2fa8f1ef7f44519767f2f2/lib/rucio/rse/rsemanager.py#L309-L311

This doesn't look too difficult unless you want to come cleaner solution.

**Comment by dchristidis** [comment]
Thanks Petr, the linked PR does exactly that.

https://github.com/rucio/rucio/pull/3628
