### ISSUE TITLE
rucio mover is not retrying stageout 3 times as it should

### ISSUE THREAD

**Issue by ivukotic** [rucio/rucio#3805]
Motivation
----------

rucio mover does not retry stage out. If it fails job is failed. Fixing this would save ~10-20 jobs/h from failing.

Modification
------------

**Comment by bari12** [comment]
I think it does at least one retry
https://github.com/rucio/rucio/blob/975d8f7cefdc647ec51ce88f81478c84a2503203/lib/rucio/client/downloadclient.py#L558
@TomasJavurek @mlassnig ?

**Comment by ivukotic** [comment]
On stage in it works. On stage out it does not. I have never seen an evidence of it in jobs logs. 
Here one: https://aipanda023.cern.ch/condor_logs_2/20-07-01_00/grid.7520343.2.out
from this job: https://bigpanda.cern.ch/job?pandaid=4774970626

**Comment by mlassnig** [comment]
Just checked the uploadclient. There's no retry there, correct. @TomasJavurek can you please look into this.

**Comment by TomasJavurek** [comment]
There used to be retries in rucio mover in pilot1. But we decided to keep it fully in clients for the pilot2.

**Comment by ivukotic** [comment]
@mlassnig can you revisit with @TomasJavurek what was agreed with Paul and Alexey? If I remember well it was on rucio mover to implement retries.

**Comment by bari12** [comment]
https://github.com/rucio/rucio/blob/3eeeca8f99e8f58fd24925e014289f23edc0c534/bin/rucio#L1043
Broke the possibility to just `rucio download <name>` without giving the `<scope>:<name>` pair. This needs to be fixed asap, since we cannot deploy the clients for users like this.

The cause of the issue is related to #3824 actually (not this ticket) - but this was all put together in one PR. Followup in #3824
