### ISSUE TITLE
change protocol selection

### ISSUE THREAD

**Issue by ivukotic** [rucio/rucio#3806]
Motivation
----------
when doing remote access rucio mover always uses protocol that the remote site configured to have the highest priority.
This prevents queues that load data through the xcache from using the xcache effectively.

Modification
------------
In case remote transfer destination has xcache, rucio mover should give highest priority to root protocol.

**Comment by bari12** [comment]
We have to think how to best do this, because we can't generalise this case in the client. The pure existence of xroot on a remote RSE should not, per default, cause the re-prioritization of the protocol order. I mean the site put it that way for a reason. And especially for communities who don't use xCaches that re-prioritization makes no sense.

A possibility would be to add a parameter `--prefer root` to the client (or to the rucio.cfg), to do that. And the pilot uses the rucio-mover like this. But it's not fully clear to me if it is a good idea to ignore the sites prioritization in all cases. And if not, then it gets difficult to make some conditional prioritization.

**Comment by ivukotic** [comment]
I don't say that if there is xroot on a remote RSE, it should automatically be prioritized.
It should be prioritized only in cases where destination has xcache.

**Comment by mlassnig** [comment]
While not too troublesome to implement, I don't think this is a good idea, because it overrides the priorities set by the source sites.

In any case, this can be forced already by giving `protocol=root` to the `rucio download`/`downloadclient/pilot` which constructs the correct XCache paths.

IMHO this should be the pilot deciding to add this parameter to the call or not.

**Comment by ivukotic** [comment]
yes this should be part of the rucio mover, right? btw: do you consider rucio mover part of rucio or part of pilot?

**Comment by TomasJavurek** [comment]
> yes this should be part of the rucio mover, right? btw: do you consider rucio mover part of rucio or part of pilot?

pilot (it is hosted in pilot git repo).

It is even more difficult. This would need to be done in pre-stages of rucio mover in the pilot. The reason is, that rucio mover gets already pfn to download from the pilot and process it. The --protocol option can be set only for the DID methods that are not used by the pilot. We could manipulate the pfn in the ruciomover in teh pilot, but that sound really wrong. Pls open a ticket for the pilot.
