### ISSUE TITLE
Some daemons CLI are missing a sleep-time option

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#3987]
Motivation
----------
Some daemons CLI are missing a sleep-time option. It needs to be added

**Comment by davidpob99** [comment]
I've been working on this and I have some questions with some daemons:

- c3po: it seems that waiting_time==sleep_time, but there is a value different for each function (read_free_space, read_workflow, ...). Should I add a command argument to change each one?
- conveyor.fts_throttler: is cycle_interval==sleep_time? Should rename the variable to sleep_time?
- conveyor.poller_latest: is fts-wait==sleep_time? Should rename the variable to sleep_time?
- follower: cannot add sleep_time because of get_thread_with_periodic_running_function
- hermes: is delay==sleep_time? Should rename the variable to sleep_time?
- oauthmanager: is loop_rate==sleep_time? Should rename the variable to sleep_time?
