### ISSUE TITLE
Multihop intermediate replica tombstone

### ISSUE THREAD

**Issue by nsmith-** [rucio/rucio#4188]
Motivation
----------
From https://github.com/rucio/rucio/pull/3064/files#r343021930 it looks like, in addition to the transfer source replica protection, an additional protection is placed on files likely to be created by a multihop transfer in setting the tombstone to (now+2h). I think these intermediate replicas should have epoch tombstone so they are cleaned up immediately rather than flushing popular but unlocked replicas from the intermediate disk RSE.

Modification
------------
There may be other uses of `update_replicas_states` besides multihop that would hit this code, so I am not sure if we want to set the tombstone to epoch always. Perhaps somewhere else we can set this? Or we can add a flag to indicate the replica is being used for multihop?

**Comment by nsmith-** [comment]
Somewhat related, I think the tombstone set on a replica that was made at the end of a transfer in https://github.com/rucio/rucio/blob/master/lib/rucio/daemons/conveyor/finisher.py#L462 should also be epoch.

**Comment by bari12** [comment]
You could also argue since the replicas was used, for the multihop, it is a valid access. But I get your point that, since the data is migrated to tape, it is just less likely that a workflow will re-access it.
We would carefully have to check if we could end up in some kind of race-condition with the epoche tombstone though, thus the intermediate replica is removed before the second hop happens. For normal transfers, this is protected, but for MH everything is a bit different. @cserf what do you think?

**Comment by cserf** [comment]
See also https://github.com/rucio/rucio/issues/4436
I would propose to have the tombstone configurable

**Comment by cserf** [comment]
Proposal:
When the finisher marks the intermediate replica as AVAILABLE in https://github.com/rucio/rucio/blob/398df650f9cd75b3befac60d3b71e031c39061da/lib/rucio/core/replica.py#L1900 , it will check what tombstone should be set using the tombstone defined in the config table. Adding a protection against race condition with the reaper(2) in case the tombstone is set to Epoch would require a change in the logic of `list_and_mark_unlocked_replicas`. I need to think what is the best solution.

**Comment by bari12** [comment]
Yes, as we have seen setting an epoch tombstone here would probably not work correctly, since it will remove the replica way to soon (See #4436)
Having a configurable tombstone in the configtable would solve both #4436 and #4188 (You can set a much shorter one, if you are sure that this works in your deployment)

**Comment by nsmith-** [comment]
I'm confused, are you saying there is a race condition in the logic and you can configure how risky you want to be with respect to it?

**Comment by rcarpa** [comment]
@nsmith- , the epoch tombstone is now default for intermediate replicas. Missing protections from deletion were added to allow that. We hope that we'll not have race conditions, but the machinery is big and fragile. The configuration parameter is there with 2 purposes: one is to allow keeping intermediate replicas for longer when it is administratively desired (high probability of re-usage of the replica). The second is the one you mentioned.
