### ISSUE TITLE
update_requests_priority() does not actually update the request priority in Rucio

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4320]
Motivation
----------

Once the FTS job is successfully updated, one would expect the request on the Rucio side to be updated too. If the FTS job fails and it’s resubmitted by the Finisher (i.e. without the replica getting stuck), won’t it use the original priority?

Modification
------------

**Comment by rcarpa** [comment]
`update_requests_priority` is only called from [`update_rule`](https://github.com/rucio/rucio/blob/40ca9a9b3f33d540a65d0279e61ab09734a8164c/lib/rucio/core/rule.py#L1368) which takes care of updating the entry in rucio at the line just before this call. Considering that `update_requests_priority` is located in `request.py`, it looks to be correctly named and located for what it does: update the priority in the FTS job. Don't think anything has to be done for this ticket. I propose to just add a small additional test.

**Comment by bari12** [comment]
It updates the rule (row in `rules` table) but does not update the specific requests (rows in `requests` table). It does update the FTS job(s), which is correct, but there is the case that the FTS job fails, which would cause Rucio to re-submit the request after some time. But since the priority wasn't updated in the request, it would re-submit with wrong priority.
Within `update_requests_priority` you can take the same selection query and issue an update of the priority at the end of the method.

**Comment by rcarpa** [comment]
Ah. Thanks. Will dig into it deeper.
