### ISSUE TITLE
Revisit "rses" filter for request retrieval

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#4405]
Motivation
----------
[__list_transfer_requests_and_source_replicas](https://github.com/rucio/rucio/blob/61cde42bda4026a1c55b87986939b7c0ec39e85d/lib/rucio/core/transfer.py#L1296) takes two arguments: `limit` and `rses` which can potentially not work correctly together. The filtering on rses is done in python, after retrieving `limit` request from database. Potentially, the desired rses can be in the database after the first `limit` ones. The function will return an empty request list, even if there are some which correspond to the desired filters.

Modification
------------

It is unclear if filtering by multiple rses is really desired. For now, no code (except tests) really use the `rses` filter code path.
Decide how to fix this issue:
- implement filtering by multiple rses directly in the query? 
- or rework the calling context to only retrieve transfers for one rse at a time and filter by single rse in the query?
- or remove the support for filtering ? 
- other solution ?

**Comment by bziemons** [comment]
> It is unclear if filtering by multiple rses is really desired. For now, no code (except tests) really use the rses filter code path.

I don't understand why it is unclear if tests need and use this functionality?
In tests (and reality) there shouldn't be too many requests accumulating and this therefore seems like a non-issue most of the times. If you want to fix filtering by rses before limiting be my guest, but I don't think there should be a high priority on this.

**Comment by rcarpa** [comment]
If the functionality is there, somebody could start using it in production without checking how it is implemented. As a compromise, we may say that the risk is low that somebody will put a long list of rses, and just do the accumulator query instead of filtering rses in python.
I got into this issue on my test setup, because I don't re-create the containers each time I run the tests. It was very confusing when tests stopped working at some random moment after some completely random unrelated change. I spent un-needed time and nerves chasing the wrong issue.
 I think that the issue must be fixed, but it is obviously a low priority.

**Comment by bziemons** [comment]
> If the functionality is there, somebody could start using it in production without checking how it is implemented.

As I said: if requests in those specific states are accumulating in production, there is a different problem and this just follows up and does not distort the picture of the actual problem.

> I got into this issue on my test setup, because I don't re-create the containers each time I run the tests. It was very confusing when tests stopped working at some random moment after some completely random unrelated change. I spent un-needed time and nerves chasing the wrong issue.

I agree that is annoying. The actual issue is that tests leave behind lots of resources in the database though. Similar errors could happen all over the place and I usually recreate my containers after test failures or when working on a different branch.

**Comment by rcarpa** [comment]
I agree that it is low priority, but I don't understand why a known race condition should be ignored. Do you prefer to close the issue as "won't fix" ?

**Comment by bari12** [comment]
In perfect conditions, it wouldn't be an issue since something would always consume the top of the queue, so eventually, things will end up at the top and consumed then. But you could imagine a case where eg. every submitter just works on one RSE. If one of them crashes, it could starve the others.

But to me the question is more, do we need that functionality at all, if yes, is it worth to fix it or is it enough to just document this kind of starvation issue.

Thinking about this, I would probably leave it in, because it can be useful for certain (temporary) integration testing, although in general it is always better if the daemons just work on everything. But spending much time on this is probably wasted time. So maybe just leave a line in the documentation (--help of the daemon) and be done with it.

**Comment by bari12** [comment]
One interesting realisation @bziemons pointed out. For `multi_vo=True` the default case (Work on all RSEs) will still generate a list of ALL `working_rses` here https://github.com/rucio/rucio/blob/3e5daa2891796222ddc2a72c40840a466f94a43f/lib/rucio/daemons/conveyor/submitter.py#L272-L274

To prevent this starvation issue, I think the default multi_vo case (all VOs, no include/exclude RSEs) should give a `working_rses=None`. Then there is no starvation. @ijjorama we should maybe look into that.

But for this issue, I would proceed like pointed out above. Just mention the starvation in the `--help`; It's not something commonly appearing.
