### ISSUE TITLE
Sync positional arguments and function names

### ISSUE THREAD

**Issue by juztas** [rucio/rucio#4477]
Motivation
----------
From the command line - we have positional arguments add-rule/delete-rule/rule-info/list-rules, but using python - it changes to add_replication_rule/delete_replication_rule... . It would be nice if these call names (function names) synced (What is on the command line, the same call is on python - for simplicity). 
Also - the command line tool is missing some positional arguments (maybe more, did not check all options), e.g. approve. 

Modification
------------

**Comment by bari12** [comment]
For the naming I don't think this should be the same. There is just different objectives for the naming of CLI commands vs methods in the python clients. For CLI commands you want them to be short and meaningful, so you are able to type them quickly. For the python clients, which offer a much larger set of functionality, the functions should be descriptive, since it doesn't matter so much how long they are. Due to the larger method space there is also a bigger risk of collisions (Something like `add_rule`).
Secondly it is always a bit of an issue to change these now, since external applications rely on the commands now. So over all I don't think this is something we should do.

For the additional CLI commands like rule-approve or rule-deny I agree. Maybe there is somebody from CMS who want's to implement these CLI endpoints?
