### ISSUE TITLE
Cleanup unused packages in pip-requires

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#45]
ntplib
etc

_Migrated from JIRA [RUCIO-2629](https://its.cern.ch/jira/browse/RUCIO-2629)_

**Comment by cserf** [comment]
Non exhaustive list :
gearman==2.0.2
git-review==1.26.0          # Command-line tool for Git / Gerrit
idna==2.6                   # Internationalized Domain Names in Applications (IDNA)
ipaddress==1.0.18           # IPv4/IPv6 manipulation library
repoze.lru==0.7             # LRU (least recently used) cache implementation.
...

**Comment by cserf** [comment]
I ran pip-extra-reqs (https://pypi.python.org/pypi/pip_check_reqs/2.0.1). Here is the list returned :
anyjson in requirements.txt
argcomplete in requirements.txt
argparse in requirements.txt
babel in requirements.txt
cffi in requirements.txt
coverage in requirements.txt
cryptography in requirements.txt
docutils in requirements.txt
enum34 in requirements.txt
flup in requirements.txt
functools32 in requirements.txt
futures in requirements.txt
gcloud in requirements.txt
gearman in requirements.txt
git-review in requirements.txt
googleapis-common-protos in requirements.txt
grpcio in requirements.txt
httplib2 in requirements.txt
idna in requirements.txt
ipaddress in requirements.txt
jinja2 in requirements.txt
mako in requirements.txt
maxminddb in requirements.txt
meld3 in requirements.txt
ntplib in requirements.txt
numpy in requirements.txt
oauth2client in requirements.txt
ordereddict in requirements.txt
paste in requirements.txt
pinocchio in requirements.txt
protobuf in requirements.txt
pyasn1 in requirements.txt
pyasn1-modules in requirements.txt
pycparser in requirements.txt
pycrypto in requirements.txt
pygments in requirements.txt
pyopenssl in requirements.txt
pytest-xdist in requirements.txt
python-editor in requirements.txt
python-memcached in requirements.txt
python-swiftclient in requirements.txt
repoze-lru in requirements.txt
rsa in requirements.txt
setuptools in requirements.txt
six in requirements.txt
tox in requirements.txt

Some modules like argparse and argcomplete appear in this list because they are already in py2.7 by default
