### ISSUE TITLE
Implement http-srm protocol

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#4506]
Motivation
----------
Some sites want to be able to enable HTTP as File Transfer Protocol instead of GridFTP. We need to implement a new http-srm protocol and add it to the list of compatible protocol for HTTP(S)/DAV(S)

**Comment by vokac** [comment]
I don't fully understand implemented URL modifications, because `srm+https` is defined in the `constants.py`
https://github.com/rucio/rucio/blob/556f2df219415421179ed8cff906032256dbfccc/lib/rucio/common/constants.py#L30-L38
but then URL is changed to `https+srm`
https://github.com/rucio/rucio/blob/556f2df219415421179ed8cff906032256dbfccc/lib/rucio/core/transfer.py#L867-L871
https://github.com/rucio/rucio/blob/556f2df219415421179ed8cff906032256dbfccc/lib/rucio/core/transfer.py#L1010-L1014
It is even less clear to me the use of `re.sub` to modify URL, e.g.
```python
>>> import re
>>> source_url = 'srm://fqdn/path/to/file_with_srm_in_name'
>>> re.sub('srm', 'https+srm', source_url)
'https+srm://fqdn/path/to/file_with_https+srm_in_name'
```
This doesn't look OK to me (and there are quite a lot of these suspicious `re.sub` replacements)

**Comment by bari12** [comment]
We already discussed this in the ATLAS DevOps meeting, but just for completion here: 
1. the mixup between `srm+https` and `https+srm` needs to be fixed. @cserf is aware of it :-)
2. It would indeed be better to just replace at the beginning of the string.

**Comment by vokac** [comment]
Thinking more about this we'll need
* FTS servers with different transfer protocol preference configuration for SRM
* Rucio support to submit to different FTS server according `srm://` vs. `srm+https://` protocol
Is is possible to choose FTS server per protocol? Added these points to DOMA TPC agenda, because this exercise is getting a bit too complicated.

**Comment by bari12** [comment]
> * Rucio support to submit to different FTS server according `srm://` vs. `srm+https://` protocol
>   Is is possible to choose FTS server per protocol? Added these points to DOMA TPC agenda, because this exercise is getting a bit too complicated.

No, that's not possible and it's something I would not want to add. It gets complicated and we should not aim to micro-manage FTS transfers at that level. For the sake of the exercise, we can possibly fake something though.

**Comment by vokac** [comment]
After thinking a bit more how FTS behaves and looking at real production transfers we don't really need one RSE with both `srm://` and `srm+https://` and than everything should work just with (fixed) updates that were already done.
