### ISSUE TITLE
Further list_replicas changes

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4603]
Motivation
----------
With #4353 the core `list_replicas` method was changed to, per default, filter replicas whose RSEs are read-disabled. This changes however the default behaviour from `rucio list-file-replicas` as this method should list replicas on read-disabled RSEs too.

We should do the following steps

1. in https://github.com/rucio/rucio/blob/57575a05ece137daac27bb0df28f0ca1a4faf560/lib/rucio/client/replicaclient.py#L121-L126
set `unavailable` per default as `True`. 
2. As `unavailable` is quite an ambiguous term, with 1.26 we should replace `unavailable` with `ignore_availability`
3. On the REST level we need to keep `unavailable`, for backwards-compatibility reasons, but should additionally add `ignore_availability` as well. This one takes then precedence over `unavailable` 
4. On an API and core level https://github.com/rucio/rucio/blob/57575a05ece137daac27bb0df28f0ca1a4faf560/lib/rucio/core/replica.py#L1238-L1244 the method parameters are ambiguous. Currently there is `ignore_availability`, `unavailable` and `all_states` which somewhat do similar functionality. `unavailable` should be removed entirely and only `ignore_availability` and `all_states ` should stay.
5. #3431 should be done, where we expand the `list-file-replicas` with actual state and RSE status information.

**Comment by rcarpa** [comment]
Looking into removing the "unavailable" parameter to finalize this issue; and I'm not sure about the implication. Unavailable is != ignore_availability. It allows to list replicas in some particular states : https://github.com/rucio/rucio/blob/8b962296ac0151b9414cbf8138937abff3441cb1/lib/rucio/core/replica.py#L696 

Do I understand correctly that this is a behavior we don't want to keep? So I must keep it on the api level so that older clients can use it for now; but I must remove it from clients because it's function overlaps a lot with the `all-states` one ?
