### ISSUE TITLE
Evaluate impact by FTS Multihop change: files transition from NOT_USED to CANCELED on multihop job failure

### ISSUE THREAD

**Issue by mpatrascoiu** [rucio/rucio#4652]
FTS introduced a change recently ([FTS-1697](https://its.cern.ch/jira/browse/FTS-1697)) for mutlihop jobs.

When a multihop job fails (a failed transfer is encountered), all files transition from `NOT_USED` state to `CANCELED`.
Previously, untouched transfers would remain in `NOT_USED` state.

The change is marked for release `v3.10.1`.

Could you evaluate the impact on Rucio side?
If there is an impact, additional consideration must be given before deploying `v3.10.1` on FTS instances used by Rucio.

Cheers,
Mihai

**Comment by bari12** [comment]
Thanks @mpatrascoiu 

We will have to investigate. From quickly looking at the code I think we would have to change Rucio code.

But an API change like this would need to be deployed in sync. It makes me wonder if we should keep track of a compatibility table with Rucio <-> FTS versions, which for now we did not do, just to make people aware of this. This change is a bit isolated and, as far as I know, would only affect ATLAS and CMS, as they are the only Multi-Hop users. I think we would have to backport this to the LTS releases at least, because there might be VOs not using Mutli-Hop now, but might activate it at some point.

But even if we are tracking these compatibilities, I think it is not ideal that the change is included in a patch release. The fact that the API/behaviour changes is probably not something expected by the admins for a patch release.

**Comment by mpatrascoiu** [comment]
I agree a patch release was not the right place for this.

I've modified the referenced JIRA ticket ([FTS-1697](https://its.cern.ch/jira/browse/FTS-1697)) and made the behavior configurable via the FTS3 config file. 

This means from FTS `v3.10.2` we can choose to enable/disable this behavior on our server-side. For Rucio FTS instances, this behavior will stay disabled until agreed otherwise.

What is important for us is this change does not prevent further fixes, which fortunately, it won't anymore.

Having a Rucio <--> FTS compatibility table is a good idea. Both services naturally evolve and it will be impossible to guarantee compatibility across all version combinations.
