### ISSUE TITLE
Automatic protocol failover for upload

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#468]
Motivation
----------
Similar to `rucio download` there should be a protocol failover mechanism in `rucio upload`, if the process does not work. This can probably be c/p in large parts.

**Comment by mlassnig** [comment]
rucio download first tries on the same site with different protocols, then hops to another site and tries the protocols available there. for the upload, we only want the different protocols, we don't want to automatically upload to another site.

**Comment by nikmagini** [comment]
Comment about the c/p suggestion: are you sure that the protocol failover in `rucio download` actually works? From a few tests and looking at the code, I don't think it's doing anything... AFAICT only the site failover works in `rucio download` but the protocol failover will always select the default (though hard to test for sure since I need to find a site where protocol 1 fails and then protocol 2 works...)

**Comment by mlassnig** [comment]
pinging @TWAtGH , the download one should work with both protocol and rse failover. something for monday ;-)

**Comment by TWAtGH** [comment]
You mean because the protocol is assigned to the 'read_protocol' attribute and then 'read_protocol' is ignored afterwards? I think you're right but for any reason its working in my tests:

>rucio -v download --ndownloader 1 user.mlassnig:user.mlassnig.pilot.test.multi.hits
2018-01-22 13:30:06,722	DEBUG	Thread 1/1 : 2 possible protocol(s) for read
2018-01-22 13:30:06,722	DEBUG	Thread 1/1 : Trying protocol davs at IN2P3-LAPP-MWTEST_DATADISK
2018-01-22 13:30:06,722	INFO	Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
2018-01-22 13:31:06,812	WARNING	The requested service is not available at the moment.
Details: An unknown exception occurred.
Details: Could not open source: Connection timed out
2018-01-22 13:31:06,812	DEBUG	Thread 1/1 : Failed attempt 1/2
2018-01-22 13:31:06,812	INFO	Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
2018-01-22 13:32:06,899	WARNING	The requested service is not available at the moment.
Details: An unknown exception occurred.
Details: Could not open source: Connection timed out
2018-01-22 13:32:06,899	DEBUG	Thread 1/1 : Failed attempt 2/2
2018-01-22 13:32:06,900	DEBUG	Thread 1/1 : sending trace
2018-01-22 13:32:06,928	DEBUG	Thread 1/1 : Trying protocol gsiftp at IN2P3-LAPP-MWTEST_DATADISK
2018-01-22 13:32:06,928	INFO	Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
2018-01-22 13:34:14,225	WARNING	The requested service is not available at the moment.
Details: An unknown exception occurred.
Details: Could not open source: globus_xio: Unable to connect to lapp-se99.in2p3.fr:2811 globus_xio: System error in connect: Connection timed out globus_xio: A system call failed: Connection timed out
2018-01-22 13:34:14,225	DEBUG	Thread 1/1 : Failed attempt 1/2
2018-01-22 13:34:14,225	INFO	Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
2018-01-22 13:36:21,457	WARNING	The requested service is not available at the moment.
Details: An unknown exception occurred.
Details: Could not open source: globus_xio: Unable to connect to lapp-se99.in2p3.fr:2811 globus_xio: System error in connect: Connection timed out globus_xio: A system call failed: Connection timed out
2018-01-22 13:36:21,457	DEBUG	Thread 1/1 : Failed attempt 2/2
2018-01-22 13:36:21,457	DEBUG	Thread 1/1 : sending trace
2018-01-22 13:36:21,492	DEBUG	Thread 1/1 : 3 possible protocol(s) for read
2018-01-22 13:36:21,493	DEBUG	Thread 1/1 : Trying protocol srm at INFN-NAPOLI-ATLAS_DATADISK
2018-01-22 13:36:21,493	INFO	Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from INFN-NAPOLI-ATLAS_DATADISK
2018-01-22 13:36:25,893	INFO	Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 successfully downloaded from INFN-NAPOLI-ATLAS_DATADISK

Anyway this should be patched maybe.

**Comment by nikmagini** [comment]
Hi @TWAtGH 

which version of the rucio client are you using? For me, protocol fallback works until rucio client version 1.14.5 - see (1)

However it doesn't work anymore with the latest rucio client 1.14.7 - see (2) where davs is always used.

At first guess it may have been broken in this commit :

https://github.com/rucio/rucio/commit/0464c8b121150ee9c523cdf6bb9105b73c855094

I'll open a separate ticket for this

Cheers
N

(1)


> [nmagini@lxplus072 ruciotest]$ lsetup 'rucio 1.14.5'
> 
> Requested:  rucio ... 
>  Setting up emi 3.17.1-1_v3.sl6umd4v2 ... 
>   Skipping: grid middleware already setup (from UI)
>  Setting up rucio 1.14.5 ... 
> Info: Setting compatibility to slc6
> Information for user <<<<<<<<<<<<<<<<<<<<<<<<<
>  emi:
>    Your proxy has 11h:57m:2s remaining
> 
> [nmagini@lxplus072 ruciotest]$ rucio --verbose download --rse IN2P3-LAPP-MWTEST_DATADISK mc15_14TeV:HITS.10075481._000455.pool.root.1
> 2018-01-22 14:41:55,610 DEBUG   RSE-Expression: (IN2P3-LAPP-MWTEST_DATADISK)&istape=False
> 2018-01-22 14:41:55,648 DEBUG   Starting 1 download threads
> 2018-01-22 14:41:55,648 INFO    Thread 1/1 : Starting the download of mc15_14TeV:HITS.10075481._000455.pool.root.1
> 2018-01-22 14:41:55,648 DEBUG   Waiting for threads to finish
> 2018-01-22 14:41:55,648 DEBUG   Thread 1/1 : Potential sources : [u'IN2P3-LAPP-MWTEST_DATADISK']
> 2018-01-22 14:41:55,725 DEBUG   Thread 1/1 : 2 possible protocol(s) for read
> 2018-01-22 14:41:55,725 DEBUG   Thread 1/1 : Trying protocol davs at IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:41:55,725 INFO    Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:41:56,082 WARNING Source file not found.
> Details: Source file not found.
> Details: Failure HTTP 404 : File not found , while  readding after 1 attempts
> 2018-01-22 14:41:56,082 DEBUG   Thread 1/1 : Failed attempt 1/2
> 2018-01-22 14:41:56,082 INFO    Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:41:56,261 WARNING Source file not found.
> Details: Source file not found.
> Details: Failure HTTP 404 : File not found , while  readding after 1 attempts
> 2018-01-22 14:41:56,261 DEBUG   Thread 1/1 : Failed attempt 2/2
> 2018-01-22 14:41:56,261 DEBUG   Thread 1/1 : sending trace
> 2018-01-22 14:41:56,296 DEBUG   Thread 1/1 : Trying protocol gsiftp at IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:41:56,296 INFO    Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:41:57,135 WARNING Source file not found.
> Details: Source file not found.
> Details: globus_ftp_client: the server responded with an error 500 500-Command failed. : System error in name: No such file or directory  500-A system call failed: No such file or directory  500-  500 End.
> 2018-01-22 14:41:57,136 DEBUG   Thread 1/1 : Failed attempt 1/2
> 2018-01-22 14:41:57,136 INFO    Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:41:58,079 WARNING Source file not found.
> Details: Source file not found.
> Details: globus_ftp_client: the server responded with an error 500 500-Command failed. : System error in name: No such file or directory  500-A system call failed: No such file or directory  500-  500 End.
> 2018-01-22 14:41:58,079 DEBUG   Thread 1/1 : Failed attempt 2/2
> 2018-01-22 14:41:58,079 DEBUG   Thread 1/1 : sending trace
> 2018-01-22 14:41:58,100 ERROR   Thread 1/1 : Cannot download file mc15_14TeV:HITS.10075481._000455.pool.root.1
> 2018-01-22 14:41:58,100 DEBUG   All threads finished
> ----------------------------------
> Download summary
> ----------------------------------------
> DID mc15_14TeV:HITS.10075481._000455.pool.root.1
> Total files :                                 1
> Downloaded files :                            0
> Files already found locally :                 0
> Files that cannot be downloaded :             1
> Completed in 2.5720 sec.
> 



(2)

> [nmagini@lxplus101 ~]$ lsetup 'rucio 1.14.7'
> ************************************************************************
> Requested:  rucio ... 
>  Setting up emi 3.17.1-1_v3.sl6umd4v2 ... 
>  Setting up rucio 1.14.7 ... 
> Info: Setting compatibility to slc6
> Info: Set RUCIO_AUTH_TYPE to x509_proxy
> Information for user <<<<<<<<<<<<<<<<<<<<<<<<<
>  emi:
>    Your proxy has 11h:59m:24s remaining
> ************************************************************************
> [nmagini@lxplus101 ~]$ cd work/
> [nmagini@lxplus101 work]$ cd ruciotest/
> [nmagini@lxplus101 ruciotest]$ ls -ltra
> total 8
> drwxr-xr-x. 13 nmagini zp 2048 Jan 22 14:10 ..
> drwxr-xr-x.  9 nmagini zp 2048 Jan 22 14:10 rucio
> drwxr-xr-x.  4 nmagini zp 2048 Jan 22 14:11 .
> drwxr-xr-x.  2 nmagini zp 2048 Jan 22 14:26 mc15_14TeV
> [nmagini@lxplus101 ruciotest]$ rucio --verbose download --rse IN2P3-LAPP-MWTEST_DATADISK mc15_14TeV:HITS.10075481._000455.pool.root.1
> 2018-01-22 14:30:53,925 DEBUG   RSE-Expression: (IN2P3-LAPP-MWTEST_DATADISK)&istape=False
> 2018-01-22 14:30:53,988 DEBUG   Starting 1 download threads
> 2018-01-22 14:30:53,988 INFO    Thread 1/1 : Starting the download of mc15_14TeV:HITS.10075481._000455.pool.root.1
> 2018-01-22 14:30:53,989 DEBUG   Thread 1/1 : Potential sources : [u'IN2P3-LAPP-MWTEST_DATADISK']
> 2018-01-22 14:30:53,988 DEBUG   Waiting for threads to finish
> 2018-01-22 14:30:54,044 DEBUG   Thread 1/1 : 2 possible protocol(s) for read
> 2018-01-22 14:30:54,044 DEBUG   Thread 1/1 : Trying protocol davs at IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:30:54,044 INFO    Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:30:54,695 WARNING Source file not found.
> Details: Source file not found.
> Details: Failure HTTP 404 : File not found , while  readding after 1 attempts
> 2018-01-22 14:30:54,696 DEBUG   Thread 1/1 : Failed attempt 1/2
> 2018-01-22 14:30:54,696 INFO    Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:30:54,862 WARNING Source file not found.
> Details: Source file not found.
> Details: Failure HTTP 404 : File not found , while  readding after 1 attempts
> 2018-01-22 14:30:54,862 DEBUG   Thread 1/1 : Failed attempt 2/2
> 2018-01-22 14:30:54,862 DEBUG   Thread 1/1 : sending trace
> 2018-01-22 14:30:54,888 DEBUG   Thread 1/1 : Trying protocol gsiftp at IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:30:54,888 INFO    Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:30:55,097 WARNING Source file not found.
> Details: Source file not found.
> Details: Failure HTTP 404 : File not found , while  readding after 1 attempts
> 2018-01-22 14:30:55,097 DEBUG   Thread 1/1 : Failed attempt 1/2
> 2018-01-22 14:30:55,098 INFO    Thread 1/1 : File mc15_14TeV:HITS.10075481._000455.pool.root.1 trying from IN2P3-LAPP-MWTEST_DATADISK
> 2018-01-22 14:30:55,239 WARNING Source file not found.
> Details: Source file not found.
> Details: Failure HTTP 404 : File not found , while  readding after 1 attempts
> 2018-01-22 14:30:55,239 DEBUG   Thread 1/1 : Failed attempt 2/2
> 2018-01-22 14:30:55,239 DEBUG   Thread 1/1 : sending trace
> 2018-01-22 14:30:55,279 ERROR   Thread 1/1 : Cannot download file mc15_14TeV:HITS.10075481._000455.pool.root.1
> 2018-01-22 14:30:55,280 DEBUG   All threads finished
> ----------------------------------
> Download summary
> ----------------------------------------
> DID mc15_14TeV:HITS.10075481._000455.pool.root.1
> Total files :                                 1
> Downloaded files :                            0
> Files already found locally :                 0
> Files that cannot be downloaded :             1
> Completed in 1.4746 sec.

**Comment by TWAtGH** [comment]
Hi,
I was using the current cvmfs version (1.13.2). With rucio testing (1.14.7) it doesnt work anymore. Seems like it is always retrying the first protocol (for me it was srm).
I'll do some more tests.
Cheers
Tobi

**Comment by nikmagini** [comment]
Hi @TWAtGH 

I opened a separate issue for the download https://github.com/rucio/rucio/issues/502 and provided a fix https://github.com/rucio/rucio/pull/503 - if it looks fine, I'll apply the same logic to upload.

Cheers
N

**Comment by TWAtGH** [comment]
Hey, how is the progress here? Because I already started refactoring the upload since it will be moved to the library.

**Comment by nikmagini** [comment]
I got the failover in the upload working in 7883be7 but I need to fix the exit statuses in case of error; I'll have time to do it mid next week. If you refactor the upload I can restart from your new version, no big loss.

**Comment by TWAtGH** [comment]
I also started replacing `return FAILURE` statements with exceptions. 
My plan is now to finish the upload part of #523 so that Tomas can push it in his repo.
I will also put in the failover during this and a couple of bugfixes and cleanups.
