### ISSUE TITLE
Non optimal use of the limit parameter in list_and_mark_unlocked_replicas 

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#4897]
Motivation
----------
Non optimal use of the limit parameter in list_and_mark_unlocked_replicas

**Comment by rcarpa** [comment]
I looked into this one today and I didn't find a solution which would satisfy me. 
One of the issues is that all filters must be put on the database side to allow correctly integrating `limit` into the query. Otherwise, we'll always have to "overshoot" and get more rows from the database; followed by a post-filtering in python. 
For example, it's exactly what we do right now: we stream and lock rows until we accumulate `limit` replicas on python side. This is combined with "skip locked" functionality supported by databases to ensure that multiple reapers don't work on the same rows. 

If  we perform everything in two steps (note: the solution proposed by @cserf using a sub-query, is also a two-step solution, only implicitly hidden in one query), we may have queries returning less than `limit` replicas, even if there are many matching replicas in the database. This is because the first query filters up to "limit" replicas. And the second query tries to lock the rows. It's highly probably that the second query will not be able to lock all the rows in a context of multiple reapers in parallel. So it will just skip them due to "skip locked". As a result, deletion will be paused for the given RSE: 
https://github.com/rucio/rucio/blob/1b68bbf6d44013b193db3f668b1e4b608e488bce/lib/rucio/daemons/reaper/reaper.py#L577

I tried to put all filters on database side in hope to be able to retrieve everything we need in one unique select query. This I successfully achieved (https://github.com/rcarpa/rucio/commit/b31e75a4e404a3df68d65428cef55ed3932f8f69), but then I realized that "for update skip locked" functionality doesn't work with queries which rely on "group by".
