### ISSUE TITLE
Review session/engine handling with SQLAlchemy

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4945]
Motivation
----------
We see a huge amount of transactions rolled back on the ATLAS DB. 5000 (out of 7000) transactions/second are rolled back. However, this is not really explainable just by Rucio application workflows.

Most likely, the way we handle sessions / engines is faulty leading to connections always being closed (+rolled back to clear) at the end, which would explain such numbers.

Modification
------------
- [ ] Review SQLAlchemy engine+connection implementation in Rucio (`lib/rucio/db/session.py`) 
- [ ] Update and fix

**Comment by rcarpa** [comment]
The session/engine is already initialized as well as it could be. We use a sessionmaker which ensures we have a singleton session for each thread. The session/connection is correctly re-used by sessionmaker as long as it's allowed to.
But, the problem comes from:
https://github.com/rucio/rucio/blob/f67cf9baf750ce3b21942a029ba60ac2967f1f58/lib/rucio/db/sqla/session.py#L306
Due to this line, each time a decorated function is called without the session argument, the session singleton is explicitly destroyed. 

Because of the `api` middle layer between flask and core, more than one function with such decorator is executed per each http api call. For example, [list_replicas](https://github.com/rucio/rucio/blob/f67cf9baf750ce3b21942a029ba60ac2967f1f58/lib/rucio/api/replica.py#L144) calls `has_permissions`, `list_replicas` and, multiple times `get_rse_name`. Each of these calls will result in a session being destroyed and re-created. 

BTW, Maybe it is already known, but for me it was a surprise that we can have dangerous race conditions if we forget to forward session object. For example:

```
@transactional_session
def a(session=None):
    do_something

@transactional_session
def b(session=None):
    session.bulk_insert_mappings(...)
    a()  # the session is commited here; the singleton is removed; the connection returned to the pool; 
    # either on previous line or the next line: an implicit rollback is executed on the connection
    session.query() # a new connection is established (re-used from the pool); a new session object created
    session.rollback()  # this will not rollback the inserted mappings 
```

**Comment by bari12** [comment]
After some discussion with @rcarpa and @mlassnig the following points are of note:
- Our session management works a bit different than expected. Due to the SQLAlchemy scoped sessions, a session is actually shared in a thread, even when two scoped functions call for a new session. This should not be a problem, but is not entirely as expected.
- The `session.remove()` call in SQLAlchemy will call for a rollback of the connection after the transaction is commited. This is to clean out the connection. There is not much we can do about it, we are using SQLAlchemy as expected here https://docs.sqlalchemy.org/en/14/orm/contextual.html
- The main issue why so many sessions are rolled back empty is due to separation between API and Core. Sessions usually only come in at the core level, but since many API calls (e.g. list_replicas) call multiple core functions, in a loop, this causes the creation and `session.remove()` of a lot of sessions. This is something which can more easily be addressed. Empty rollbacks will still happen, but should be significantly less.

Actions:
- Move the session handling already to the API level. Thus also scope API methods and hand the sessions over. First we can do this with the big methods as a proof-of-concept (list_replicas, list_dids, etc.) and then continue with everything else.
