### ISSUE TITLE
Dynamic distance between RSEs

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5012]
Motivation
----------

For now, the shortest path computation and source selection is completely static. This can result in overloaded RSEs while other sources are completely unused. 

Modification
------------

We would like to make the decisions more dynamic and dependent on the load

**Comment by rcarpa** [comment]
As first step, maybe use the backlog request queue length as a weight in sorting

**Comment by rodwalker** [comment]
Hi,
I think the numbers on
https://atlasdistributedcomputing-live.web.cern.ch/ATLASDistributedComputing-live/#Satellites
come from some huge json, ultimately from rucio - so the information is there.
http://atlas-adc-netmetrics-lb.cern.ch/metrics/latest.json

The CERN-PROD queued input 30k and estimated transfer time of 19hrs matches somewhat with what I see in FTS
https://fts3-atlas.cern.ch:8449/fts3/ftsmon/#/?vo=&source_se=davs:%2F%2Fxrootd.echo.stfc.ac.uk&dest_se=davs:%2F%2Feosatlas.cern.ch&time_window=2

The #active is limited by the outbound total for RAL.

I think almost anything will be better than static.

Cheers,
Rod.

**Comment by rcarpa** [comment]
I performed the internal work in rucio to allow taking into consideration the queues and the historical transfer data for source selection. By historical data, I mean the information available in the "Transfer Plots" section of the ATLAS "DDM Transfers" dashboard. 

At this point I'm quite blocked because there is no consensus even within the team if we should be more intelligent in source selection. 
We must define a strategy. Implement it. And test it in ATLAS. I don't see any other way forward. This means accepting the risk of actually doing things worse.

**Comment by rodwalker** [comment]
So we are talking about taking the source selection away from FTS and giving it a single source replica? I think it can take an ordered list too, to allow some failover. If this new behaviour could be triggered by some attribute to the rule, e.g. priority, then maybe it could be tested without breaking what we have. Or could do like the pilot and 1% of  transfers use the dev schema(and are tagged as such). So I am in favour of just trying it.

It would be nice to have some metric, other than "Rod is moaning a bit". Something like the mean transfer time for files with multiple disk replicas.
After excluding non-functional or very slow connections, the main criteria will be the queued transfers. This would include file size as well as number, since we move a lot of 20GB files now. Time to transfer is Nf*Tf + Nmb/mbpersec and we order sources by this. Tf ~10s, is the overhead for transferring even a very small file.
In theory activity shares should be taken into account, since we only want to count files to be transferred before our file. Channel bandwidth is split between the active shares. For sure it is important to bootstrap channels with nothing transferring and nothing queued.
