### ISSUE TITLE
test_upload_download of test-server fails

### ISSUE THREAD

**Issue by deesto** [rucio/rucio#5023]
Hi,

While debugging local Rucio instance issues, I ran into what appears to be a bug in the `test-server` command of test_rucio_server, which includes three functions: ping, upload/download, and whoami. In my case, ping and whoami work perfectly, but the upload/download test fails:
`test_upload_download (rucio.tests.test_rucio_server.TestRucioClient)
CLIENT(USER): rucio upload files to dataset/download dataset ... $ > rucio upload --rse MOCK-POSIX --scope mock /tmp/rucio_testfile_142beb3df6414f4eb0fc25e9f0f421cd /tmp/rucio_testfile_633e06e79c8b4efd8ccb87fa281941cf /tmp/rucio_testfile_8bc0a1cef65b4ebaaf24c0fcb0b2b0fd mock:tests.rucio_client_test_server_7c2a3dd60d424d7f99de09d8c4778560
2021-11-19 04:10:57,912	ERROR	'function' object has no attribute 'debug'
2021-11-19 04:10:57,912	ERROR
Rucio exited with an unexpected/unknown error.`

Full output:
[rucio-server-test-output.log](https://github.com/rucio/rucio/files/7565434/rucio-server-test-output.log)

This was tested from a WN at KEKCC, using the Belle II Rucio service at BNL (blrucio.sdcc.bnl.gov).  Let me know whether this is useful or more info is needed. Thanks.

**Comment by joeldierkes** [comment]
Hello @deesto,

thank you for reporting the bug.

The `test-server` command is used in our test-environment in the first place. The workflow is coupled to some test-settings, like the existence of one RSE with the `test_container_xrd` attribute. If none of these exist, a default RSE is selected (`MOCK-POSIX`, also used in your case as seen in the logs). If you want to run the command, please make sure that your environment meets the criteria.

https://github.com/rucio/rucio/blob/9897a55fc9d0a3b00041dccc05380a2b12b06776/lib/rucio/common/test_rucio_server.py#L41-L53

I was not able to replicate the bug in my environment. I tried different configurations, like no RSE with the required attribute and different versions (`1.26.4` and the newest). The origin of the bug is a wrong initialized log variable, I couldn't find that one. Due to changes in Issue #4220 this problem could already be resolved.

After a little chat with @bari12 we will disable the problematic test function for environments which not meet the criteria.  Please let us know if this bug is reoccurring.

**Comment by deesto** [comment]
Hi @joeldierkes, and thanks for the reply. We can repeat this result by testing against the Belle II Rucio service at BNL (blrucio.sdcc.bnl.gov), which is also v1.26.4. But you are correct, of course, that there is no `test_container_xrd` variable set in my production B2 environment. So, apologies for bringing up this issue, but thanks for the fix. We are trying to track down the cause of [another issue](https://github.com/rucio/rucio/issues/5021) and wanted to use all available tools.

**Comment by bari12** [comment]
Backport 1.26.12
