### ISSUE TITLE
option for expiry date instead of lifetime

### ISSUE THREAD

**Issue by robbarnsley** [rucio/rucio#5069]
As far as I can tell, there doesn't appear to be an explicit option in the upload client to set an expiry date in place of a lifetime. 

The majority of our workflows natively use an expiration date. It would be good to have an option for the former, with an exception raised if both lifetime and expiry are specified. I recognise that there may be some timezone implications with this.

**Comment by bari12** [comment]
Timezone should be fine, we treat everything in UTC.

Just to understand, you mean the expiration time of the replica itself (thus the tombstone)?

**Comment by robbarnsley** [comment]
> Timezone should be fine, we treat everything in UTC.
> 

I mention this more from a user's perspective, that is, enforcing a user to specify a timezone when declaring an expiration date. One can imagine that a user may just input this date in local time.

> Just to understand, you mean the expiration time of the replica itself (thus the tombstone)?

Yes.

**Comment by bari12** [comment]
With timezones we have to be a bit careful. Because this would need to be everywhere in the client/REST, otherwise you get mixed results. I am not against it, but it is a change in many places. Just assuming everything is UTC would be easier.

But your usecase is for `rucio upload --lifetime`? In that case it would not be the replica tombstone but the rules lifetime (Well expiration time)

**Comment by robbarnsley** [comment]
> But your usecase is for `rucio upload --lifetime`? In that case it would not be the replica tombstone but the rules lifetime (Well expiration time)

I've misunderstood. Yes, I want it to be equivalent to `rucio upload --lifetime`, i.e. setting the rule lifetime accordingly.

**Comment by bari12** [comment]
That can be done, I would just make this convert into lifetime client-side though.
