### ISSUE TITLE
Allow the use of checksum/hash algorithms other than Adler32 and MD5

### ISSUE THREAD

**Issue by mkszuba** [rucio/rucio#5079]
Motivation
----------

Now that thanks to #3494 the use of either Adler32 or MD5 is governed by the schema in use for specific Rucio deployment, why not take it a step further and allow other algorithms to be used as well? Ideally this would be done in modular fashion so that instead of requiring Rucio developers to maintain support for each and every algorithm requested by the users, they could be added by users themselves and only optionally upstreamed.

The main motivation behind this suggestion is that while there are many file systems and storage solutions out there which now calculate data checksums, only a handful of them support algorithms currently supported by Rucio. With the latter extended to support more algorithms, one could in theory take advantage checksum information from the underlying storage - thus reducing CPU load.

Modification
------------

Off the top of my head:

1. This will almost certainly require a change of some of the API functions so that instead of _adler32_ and _md5_ keywords there is a single, unified one accepting many different algorithms - something along the lines of:

```
[
  { 'algorithm': 'foo', 'value': 0xdeadbeef },
  { 'algorithm': 'bar', 'value': 0x123456789abcdef },
  ...
]
```

2. Modify rucio.common.utils so that the list of supported algorithms is computed on the fly (e.g. by parsing available submodules containing implementations) instead of being hard-coded.

3. Also in rucio.common.utils, expose calls to loaded algorithms in well-behaved fashion so that other parts of Rucio code know how to call algorithms requested by the current schema.

4. Remove any non-schema-controlled references to adler32 and md5 elsewhere in the code.

**Comment by bari12** [comment]
Hi Marek,

This is also partly lined out in #2410, which is a quite old ticket already. I like the idea of generic checksums, the main difficulty I see is that some protocols (actual protocol implementations) only support certain checksums, so one would have to be careful about that.

Then there is of course the operational angle of this, if you run your rucio system with different checksums all over the place, this might not be a great for third party copy, but that's not for us to figure out, the community just has to be aware of it.

Maybe somebody from the community is interested to take this on?

**Comment by paulmillar** [comment]
I'd be interested to learn which checksum algorithm(s), specifically, that would be of interest to FAIR.

We can add support for new checksum algorithms to dCache, if that would be helpful.

**Comment by mkszuba** [comment]
> I'd be interested to learn which checksum algorithm(s), specifically, that would be of interest to FAIR.
> 
> We can add support for new checksum algorithms to dCache, if that would be helpful.

Nothing fancy at the moment, Lustre at GSI uses CRC-32c because although Lustre does support Adler-32, IIRC (I do not work directly with GSI Lustre) the former algorithm performs better on our hardware. Thanks for the offer to add new algorithms to dCache but it may not necessarily be useful - the key here is being able to use checksums already computed by the storage with Rucio, and that obviously means a specific checksum algorithm must be supported on _both_ ends. That said, the storage does have to be able to provide checksums for the whole files rather than, say, individual inodes, so unless dCache can already do this (sadly, I do not know if it does) you might want to look into it!

**Comment by paulmillar** [comment]
Some comments -- based on my own experience and (limited) knowledge.

CRC32c is calculated on the entire byte-stream of a file, much like ADLER32 and MD5.

I didn't really understand your comment about "individual inodes", but perhaps you're referring to the possibility to calculate checksums on parts of a file (e.g., Tiger/Merkle tree algorithms).  In which case, no, dCache currently doesn't support any checksum tree algorithm.

A little monologue on checksums ...

As an algorithm, CRC32 was developed _way_ back, when CPU and transmission technologies were operating at comparable rates -- or CPUs were slightly slower.  This meant that designing a checksum algorithm needed to be done very carefully, based on the available logic gates in the CPU.  An implementation of CRC32 can be very fast.

However, for some time now, CPUs are substantially faster that even their core memory, let along secondary storage (like hard disks).  The IO subsystem and the underlying storage bandwidth are now bottlenecks, which a CPU often idling while attempting to write data to disk.  IIRC, in a simple (non-specular) CPU model, a level-1 cache miss stalls the CPU for many hundreds of CPU cycles.  Waiting for a hard disk to accept data is like an eternality.

This applies to such an extent that I've heard of HPC centres that playing with compressing the data on-the-fly, before writing to storage.  This is _not_ to reduce the storage capacity requirements, but because it makes better use of the IO subsystem (information has higher entropy).  This is even with relatively expensive algorithm, like LZ77: the CPU is idling so much that it still makes sense.

The important part here is that calculating the checksum(s) takes place while the CPU is otherwise idle, and operates on data while it is in the L1 cache, ideally using the CPU's parallelisation (MMX, etc).

I believe (but I'm willing to be proved wrong ;-) that, with a little care, the task that writes data to the disk could calculate several checksums concurrently without any impact on the write performance.  For example, it could calculate an CRC32c checksum and another checksum (MD5, say).  The CRC32c could be used to verify data integrity on the underlying hardware, while the other algorithm provides better data-integrity security.

Anyhow, back to the topic.

I think adding support in Rucio for an extra checksum algorithm only really makes sense if checksums (calculated with that new algorithm) are subsequently used to verify a file's data integrity; for example, when transferring data.  This, in turn, means Rucio would need a way of obtaining that checksum.  Rucio could download the data and verify it that way, but normally it delegates responsibility to the storage system.  Therefore, you would require all storage systems you use to support providing checksum values based on this new checksum algorithm.

According to [this Wikipedia page](https://en.wikipedia.org/wiki/File_verification):

> As of 2012, best practice recommendations is to use SHA-2 or SHA-3 to generate new file integrity digests; and to accept MD5 and SHA1 digests for backward compatibility if stronger digests are not available. The theoretically weaker SHA1, the weaker MD5, or much weaker CRC were previously commonly used for file integrity checks

ADLER32 is also not mentioned.  IIRC, this is broadly on a par with CRC32, so also not really good enough.  ADLER32 has a lot of legacy / inertia within WLCG, but there's a (slow) transition to MD5 -- mostly because that's what external services (e.g., Amazon S3) are using.

For comparison, dCache supports ADLER32, MD5, SHA-1 and two of the three SHA-2 algorithms: SHA-256 and SHA-512.  I think SHA-384 doesn't really make much sense when protecting a file's data integrity.

**Comment by mkszuba** [comment]
> CRC32c is calculated on the entire byte-stream of a file, much like ADLER32 and MD5.
> 
> I didn't really understand your comment about "individual inodes", but perhaps you're referring to the possibility to calculate checksums on parts of a file (e.g., Tiger/Merkle tree algorithms). In which case, no, dCache currently doesn't support any checksum tree algorithm.

What I meant here was, since Rucio uses checksums of whole files in order to verify replicas if we want to feed checksums computed by storage directly into Rucio the storage system must compute checksums on whole files as well; checksums computed per data inode / extent / object / whatever the system uses under the bonnet would not be useful here. I've mentioned the issue here because I not know how checksumming works in Lustre, and having though about it some more realised that distributed storage systems are more likely to compute internal checksums on chunks of data (as that is what gets distributed across OSDs) than on files themselves.

> However, for some time now, CPUs are substantially faster that even their core memory, let along secondary storage (like hard disks).

Yes, especially with more and more ISAs supporting low-level hashing functionality (let's leave aside the problem of different ISAs supporting different hashes, leading to noticeable performance differences of same algorithms on qualitatively similarly powerful CPUs between _e.g._ amd64 and arm64). Hence such fun ideas like using compressed RAM regions as swap space, or the on-the-fly compression of stored data you have mentioned.

> I believe (but I'm willing to be proved wrong ;-) that, with a little care, the task that writes data to the disk could calculate several checksums concurrently without any impact on the write performance. For example, it could calculate an CRC32c checksum and another checksum (MD5, say). The CRC32c could be used to verify data integrity on the underlying hardware, while the other algorithm provides better data-integrity security.

I agree! And it seems some modern file systems (unfortunately I can't recall which ones, even though I only read about it this autumn) have begun to tread down this path too, introducing internal parallel support for "fast" and "strong" checksums (which funnily enough is not unlike what we have got in Rucio with separate fields for adler32 and md5, although the preferred choices _du jour_ appear to be xxhash as the former and either SHA-2 or BLAKE2 - for some reason I haven't looked into there seems to be resistance against Keccak AKA SHA-3 - as the latter). That said, the subject of optimising checksum calculations within Rucio feels like tangential to the issue at hand - my primary rationale for wanting to make it possible to support other algorithms has been, as mentioned above, to facilitate injection of checksums/hashes already computed by the storage systems, thus doing away with some of Rucio-level calculations altogether.

> I think adding support in Rucio for an extra checksum algorithm only really makes sense if checksums (calculated with that new algorithm) are subsequently used to verify a file's data integrity; for example, when transferring data. This, in turn, means Rucio would need a way of obtaining that checksum. Rucio could download the data and verify it that way, but normally it delegates responsibility to the storage system.

Correct me if I am wrong but I don't think this is entirely the case here. Two cases to the contrary that I can think of:
 * on the storage side - even though we have for performance reasons been disabling this _en masse_ in the ESCAPE data lake since the FDR, having just glanced at the code I am fairly confident that the default behaviour is still for Rucio to perform checksum verification on replicated data by itself;
 * on the client side - registering a new file replica with Rucio requires (at least for several of the currently available schemas, the default one included, anyway; I suppose that in theory one could have a schema which disables this) the knowledge of at least one checksum of the file in question. In case of the replica having been registered as a step of `rucio upload`, I am pretty sure that the required checksums are calculated by rucio-clients themselves.

> Therefore, you would require all storage systems you use to support providing checksum values based on this new checksum algorithm.

Not necessarily. After all, there is always the option of falling back to the current behaviour having bits of Rucio compute checksums.

>  but there's a (slow) transition to MD5 -- mostly because that's what external services (e.g., Amazon S3) are using.

Transition **to** MD5. Heh. Okay, there probably is (or perhaps was when the decision was made and it's just been taking so long) a good reason for this - but given my personal experience suggests it is pretty difficult to find a non-legacy service out there that does not support at least SHA-256 (pretty sure Amazon S3 does), I can't help but chuckle.

**Comment by bari12** [comment]
This is basically described by #2410
