### ISSUE TITLE
server should respond with a HTTP 503 in case of ‘Details: QueuePool limit of size X overflow X reached, connection timed out, timeout X’ 

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#5080]
Motivation
----------

Such errors can happen when one of the backends is exceptionally busy. The BaseClient has a retry mechanism, which should protect against this, but only acts on certain HTTP errors.

https://github.com/rucio/rucio/blob/226a9f8efb0dfe09b52607cd2333e184ab88d105/lib/rucio/client/baseclient.py#L85

Modification
------------

Check if a HTTP 500 is returned when this error happens and, if so, replace with a 503 (service unavailable) instead.

**Comment by bari12** [comment]
We could catch for the Rucio `DatabaseException` in the REST and raise this to the client. Right now it is not caught, and per default raises a `500`.
So this would have to be added here
https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/lib/rucio/web/rest/flaskapi/v1/common.py#L61-L84
by checking for `DatabaseException` and possibly also `QueuePool` in the error. I wonder though if we accelerate a Session pool issue due to the retries, but in general it's probably still the right thing to do.

**Comment by sayang14** [comment]
Hi @bari12 !, Can I have a try with this issue if someone is not currently assigned yet?

**Comment by bari12** [comment]
Yes sure! Please go ahead 👍

**Comment by sayang14** [comment]
Thanks a lot!, I will take it from here

**Comment by sayang14** [comment]
> by checking for `DatabaseException` and possibly also `QueuePool` in the error. I wonder though if we accelerate a Session pool issue due to the retries, but in general it's probably still the right thing to do.

Hi @bari12 , can you help me with this issue by telling about it in details especially the last line you said relating to DatabaseException and QueuePool if some error is not being caught? 
Also I would like to know if this is the function (https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/lib/rucio/web/rest/flaskapi/v1/common.py#L61-L84) for raising the default which you are talking about? Thanks!

**Comment by bari12** [comment]
Yes this is the correct location. Maybe have a chat with @joeldierkes , he wanted to include some of the common errors (DidNotFound, RuleNotFound, etc.) in this handler anyway.

**Comment by sayang14** [comment]
Hi @joeldierkes , can you please help me with this issue by telling about this in details? Thanks!
