### ISSUE TITLE
list_dids in release 1.27.x

### ISSUE THREAD

**Issue by panta-123** [rucio/rucio#5126]
Motivation
----------
I am having a issue in list_dids method .
In release 1.27.x (1.27.2):
```
>>> from rucio.client import Client
>>> c = Client()
>>> c.list_dids('users.anil123', {'name':'/belle/user/anil123/*'}, did_type = 'container')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/belle.kek.jp/grid/rucio-clients/new/lib/python2.7/site-packages/rucio/client/didclient.py", line 93, in list_dids
    raise exc_cls(exc_msg)
rucio.common.exception.KeyNotFound: Key does not exist.
Details: filters

```

But the same command works for 1.26.x (1.26.4)
```
>>> from rucio.client import Client
>>> c = Client()
>>> c.list_dids('users.anil123', {'name':'/belle/user/anil123/*'}, type = 'container')
<generator object _load_json_data at 0x7f79fc38eeb0>

```
What i am missing here? The only change i see is change in name of argument from type -> did_type (1.26.x -> 1.27.x).

**Comment by bari12** [comment]
I suspect that Belle II servers are still running on 1.26.* (You can do a `rucio ping` to confirm, or otherwise @cserf can confirm).
I am not 100% sure that the 1.27 clients would break this functionality though (@robbarnsley can you confirm?) but in principle we cannot guarantee that newer clients (of a new feature release line) work with servers running oder releases.

If this is not the case, then the issue is somewhere on server-side code 😄

**Comment by panta-123** [comment]
@bari12 Yes the server is using 1.26.x . (1.26.0)

**Comment by robbarnsley** [comment]
The 1.27 client is not compatible with the 1.26 server (the 1.26 server REST search endpoint will not be able to understand the payload sent from a 1.27 client).
