### ISSUE TITLE
bulk get replica availability

### ISSUE THREAD

**Issue by ivmfnal** [rucio/rucio#5153]
Motivation
----------
DUNE use case would benefit from the functionality of bulk retrieving of replica availability for a RSE for multiple (~10K) DIDs in an efficient way.

Modification
------------
investigate scalability of existing list_replicas() method and see if some optimization is needed/possible

**Comment by bari12** [comment]
We already talked about this on Slack, I will just put it here in case other people have comments too.

Since you would also like to have URLs returned, my main question would be, what's the difference then to a normal `list_replicas` call. This one already allows to specify `dids` and an `rse_expression`, and does return URLs. The issue will be, that it probably won't scale well to an input of 10k+ DIDs, but instead of creating a new method, it is probably better to work on that scalability until we identify some other differences between this usecase and `list_replicas`.

**Comment by ivmfnal** [comment]
Thanks Martin. I updated the issue.

**Comment by ivmfnal** [comment]
With Brandon's help, I tested list_replicas performance on DUNE Rucio version 1.29.12, which is Postgres 14. I ran list_replicas on 10K files with and without temp tables enabled. The results are:
* with temp tables: 13 seconds/10K DIDs
* without temp tables: 20 seconds/10K DIDs

The conclusions:
* the timing is significantly better than it used to be at the time when this issue was created
* while temp tables option shows ~2 times improvement, either way the timing is acceptable at the scale of 10K DIDs in request

I think this issue can be closed for now.
