### ISSUE TITLE
Better way to deal with configuration / permissions / policy

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#533]
Motivation
----------
Right now the different configuration/permissions (atlas, cms) are part of the core repository. This is not sustainable in the long term. There should be a better way to manage these e.g. separate packages and inclusion via entry points etc.

**Comment by bari12** [comment]
This was discussed in the [Dev Meeting on 2018-10-11](https://indico.cern.ch/event/760955/)
Two things should be added:
- Mentioning a module in the Rucio CFG which should be loaded. This module can be part of a config package (e.g. from ATLAS or CMS) which is installed via PyPi
- Alternatively also directly mentioning the path of a python file should be possible, which is loaded (More suitable for small experiments who do not want to package their configs)

**Comment by jamesp-epcc** [comment]
I've written some code to load the experiment-specific stuff from an external module: https://github.com/rucio/rucio/pull/2842. It will definitely need more work but I thought it might be a useful starting point for discussion.

**Comment by mlassnig** [comment]
Thanks James, I'm going to have a look.

**Comment by jamesp-epcc** [comment]
I am not sure how best to take this forward. My main concern is how we would switch to the new policy packages without breaking existing installations. We would need packages to be available for all the VOs that need them - I could create the initial packages but I don't think I am the right person to maintain them since I have no connection with most of the VOs. We also need to make sure the right packages get installed so that everything continues to work, including for the tests.
There is also the multi-VO issue. I think we will want each VO to be able to have a different policy package but this would need quite significant changes to the code and I am not sure how best to do this.

**Comment by bari12** [comment]
I think for the beginning we need some kid of dual stack solution. We would keep the current policies we have in the core package (cms, atlas, belle,...) and use them and notify these organisations that we will take the policies out of the core package within one or two feature releases. (Thus 4-8 month time) - We would also show them how to produce their own policy packages. (So we need good documentation for that)
During that time they can either provide a policy package in the config, or still use the files included in the repo. I don't think we need to prepare these for everyone, just show them how to create them and have some best practice recommendation.

The Multi-VO I would leave out of the picture for now. The current multi VO development does not support multiple policies, it should eventually, but I would do this step by step: Let's get the single VO packages working first and then also see with Eli, who will continue the Multi VO development in February.

**Comment by jamesp-epcc** [comment]
That all sounds sensible. I'll work on making my current code into a dual stack version. The pull request for this already contains some documentation about building the policy packages.
