### ISSUE TITLE
Possible regression in `rucio download --nrandom`

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5418]
Motivation
----------
In #4626 the `--nrandom` option of rucio download was changed to be able to handle very large datasets as well, by doing a smart random selection on the server side. It seems that in a recent change (Possibly 1.28?) this does not work anymore though.

```
rucio download --nrandom 1 mc21_13p6TeV.601229.PhPy8EG_A14_ttbar_hdamp258p75_SingleLep.simul.HITS.e8357_e7400_s3775
2022-03-30 12:15:53,836	INFO	Processing 1 item(s) for input
2022-03-30 12:15:54,029	INFO	Selecting 1 random replicas from DID(s): ['mc21_13p6TeV:mc21_13p6TeV.601229.PhPy8EG_A14_ttbar_hdamp258p75_SingleLep.simul.HITS.e8357_e7400_s3775']
2022-03-30 12:20:54,036	ERROR	ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

Modification
------------
Investigate the issue and fix.

**Comment by rcarpa** [comment]
The error message should probably be improved, but there is no particular regression on nrandom. The issue with this particular container is that it contains 100k + files (according to 'rucio stat');

Because of some filtering done in python, we cannot rely on database-side random. All replicas are fetched anyway from database, but then a random filter is applied on server side later. 

That being said, I think it may be possible to perform the random selection on database-side if the list_replica call doesn't specify any of the parameters which require filtering in python. Such as "schemes"
