### ISSUE TITLE
Bus error (core dumped) with rucio download on lxplus/EOS

### ISSUE THREAD

**Issue by glushkov** [rucio/rucio#5462]
Motivation
----------
Several users have reported `Bus error (core dumped)` when downloading files with the client (report [1](https://groups.cern.ch/group/hn-atlas-dist-analysis-help/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Fhn%2Datlas%2Ddist%2Danalysis%2Dhelp%2FLists%2FArchive%2FRucio%20downloads%20failing&FolderCTID=0x01200200FB8F64B0E343CB4680DEAC546A9DF813), [2](https://groups.cern.ch/group/hn-atlas-dist-analysis-help/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Fhn%2Datlas%2Ddist%2Danalysis%2Dhelp%2FLists%2FArchive%2FError%20while%20downloding%20the%20container%20from%20Panda&FolderCTID=0x01200200FB8F64B0E343CB4680DEAC546A9DF813)). 

Observations: 
* The problems appears when issuing `rucio download user.meiqi.410470.e6337_e5984_s3126_d1677_r12711.tdd.trigger.2022-03-15T2101.2022-04-04-T173216_output.h5`
   * It is confirmed to appear when saving on EOS.
   * It appears on different files
   * It is not observed on local file system (tested up to 170 GB)

**Comment by bari12** [comment]
@glushkov @dchristidis and myself did quite some testing around this and it looks like the issue comes from the new checksumming with mmap (At least on lxplus), since the issue even persists for already downloaded files, so it can't really be gfal/protocol.

The coredump stacktrace also includes

```
:#5  0x00007fac1d857188 in mmap_read_method () from /usr/lib64/python2.7/lib-dynload/mmapmodule.so
:#6  0x00007fac2b34e073 in PyObject_Call () from /lib64/libpython2.7.so.1.0
:#7  0x00007fac22f9c8e1 in partial_call () from /usr/lib64/python2.7/lib-dynload/_functoolsmodule.so
```

For `1.28.2` I would suggest we disable the `mmap` based checksumming and return to the old procedure. Once Mario is back from vacation he can maybe do a deeper investigation, perhaps there is a fix which still allows us to use mmap.
