### ISSUE TITLE
Rest Api ListReplicas endpoint should be GET

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5516]
Motivation
----------
The Rest Api `ListReplicas` endpoint should be a GET request, it is a POST.
https://github.com/rucio/rucio/blob/2e3ad40fc1e64abb35e1e4e4bd5cddec9701d3f9/lib/rucio/web/rest/flaskapi/v1/replicas.py#L299

Modification
------------
Change the `ListReplicas` endpoint request type.

**Comment by mlassnig** [comment]
Careful with this.

We have two different types of clients right now, one expects the POST to come back as application/x-json-stream (one full json per entry per line returned), the one that expects GET to come back as application/x-json (one full json reply containing everything).

Adding @davidgcameron for info (since ARC is using the GET case)

**Comment by joeldierkes** [comment]
Yes, some explanation would be nice. Specifically:
- The `GET` method in HTTP is used to request data, the `POST` is used to create/update data. In the `ListReplicas` endpoint, the data is only requested, not updated/posted. Why don't we have two separate endpoints or a header variable to distinguish that instead of the `POST` request? We're already doing that for the metalink case:https://github.com/rucio/rucio/blob/2e3ad40fc1e64abb35e1e4e4bd5cddec9701d3f9/lib/rucio/web/rest/flaskapi/v1/replicas.py#L376
- The `GET` method is not implemented for the `replica/list` endpoint, where is it coming from? https://github.com/rucio/rucio/blob/2e3ad40fc1e64abb35e1e4e4bd5cddec9701d3f9/lib/rucio/web/rest/flaskapi/v1/replicas.py#L890

**Comment by bari12** [comment]
The issue here is historic. `POST` was chosen (instead of `GET`) due to the header-size limitations of a get. Thus much less replicas could be asked for in a list_replicas. However, this could probably have been solved differently by addressing these limits in apache (I believe there is a setting for that)

To move forward:
- Investigate the setting in apache
- Duplicate this endpoint as a `GET` endpoint (Leave the `POST` as it is)
- Over time we might be able to deprecate the `POST` endpoint

**Comment by rcarpa** [comment]
This can be a good opportunity to split the logic which list replicas and the one generating the URLs / (authentication credentials) associated with the replicas for accessing them. This will avoid spending CPU time signing URLs which are not used afterwards at all.

**Comment by bziemons** [comment]
@bari12 and I have talked a bit about the options for this issue. Utilizing HTTP headers for the search data is very unusual in Rucio and everywhere else and I think it should be avoided.
Also, currently there are no GET requests with request body except for [this rules endpoint](https://github.com/rucio/rucio/blob/3df51d61a1c2d27564b2fa305e55c74562c9f725/lib/rucio/web/rest/flaskapi/v1/rules.py#L39), where the request body usage will be removed in the future. Using a GET request with request body is not cacheable and not recommended:

![image](https://github.com/rucio/rucio/assets/1096713/f1d76f31-c800-411a-861c-9b9dab074120)
Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

Utilizing GET parameters (query parameters) seems like it is not a good fit for this usage neither, because the amount of data we currently could have in the request body exceeds usual URL length limits. Ultimately, a GET request with query parameters would be the preferred solution though.

Furthermore, there is quite a bit of discussion of how to handle a "search"-like RESTful endpoint as can be seen in [this Stack Overflow answer](https://stackoverflow.com/a/18933902). While the answer suggests a search endpoint with POST method, others claim in the comments that this would be bad design and [links to a similar question's answer](https://softwareengineering.stackexchange.com/questions/233164/how-do-searches-fit-into-a-restful-interface). The answer states it is bad because they cannot copy-paste the search URL into a standard web browser see the search results. Not sure how relevant that comment is though, since a RESTful API is usually not browsed by a standard web browser.

We concluded it would be best to keep the current API, even if it is odd. It fits the technical needs best, as it currently stands.
