### ISSUE TITLE
Make subscriptions page real-time

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#5583]
Motivation
----------

https://github.com/rucio/rucio/blob/86390dfa9e6a99d82a315a2733ba06f6687c4bb4/lib/rucio/web/ui/static/rucio.js#L1687

The Web UI appears to depend on dumps to populate the information on the subscriptions page. This can cause problems if the production of these dumps is disrupted or never configured in the first place. In addition, there seems to be some time-related calculation that is not timezone-agnostic.

Modification
------------

Evaluate the effect of fetching the information from the database in real-time and consider switching to it.

**Comment by maany** [comment]
Hey @nimishbongale, after a quick chat with @cserf, it turns out that you can replace the dumps with the following endpoints on the rucio server (pick one that works best):
https://github.com/rucio/rucio/blob/730ea648608292cff6cd69afb10113090a5064f2/lib/rucio/web/rest/flaskapi/v1/subscriptions.py#L263-L266

**Comment by nimishbongale** [comment]
Great!

I'll do the needful. Thanks @cserf @maany

**Comment by dchristidis** [comment]
I’m afraid that the implementation is faulty.

```
Uncaught ReferenceError: acc is not defined in subscriptions.js:26:13
```
