### ISSUE TITLE
OIDC login in webui not working in 1.29

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#5719]
Motivation
----------
The OIDC login in 1.29 fails for me in the last step in the Webui when the authentication is finalized. The authentication server should set the `x-rucio-auth-token` cookie before the browser is redirected to `oidc_final` but with the changes introduced in https://github.com/rucio/rucio/pull/5580/commits/57459660a8d22af3c1d768cb340852e3606595f4 the cookie isn't set for me. Neither in Firefox nor Chrome. If I manually revert the change the login works again correctly.

**Comment by bari12** [comment]
So I fixed this by reverting the commit in 1.29, but this should still be looked at in more detail.
@rizart

**Comment by rizart** [comment]
Yeah, I remember not being very confident about this change. What I remember though is that this was needed in order to make the flow functional in some cases where two `x-rucio-auth-token` cookies are set and the server complains when the token expires as it is trying to always use the old token to authenticate (the issue was bypassed if you manually cleared your cookies) - this must be connected with how the dev environment is configured (`<hostname>/auth`, `<hostname>/ui`, etc.). Anyhow, I can take a better look once back from vacation!

**Comment by rizart** [comment]
I can confirm that reverting the commit produces a buggy behavior, at least for ESCAPE. It works fine initially, but once the first token expires you are not able to login again if you don't clear your cookies (it's the double `x-rucio-auth-token` cookie as I mentioned before, in our case the `.cern.ch` domain cookie gets replaced with the new token, but the `escape-rucio-webui.cern.ch` domain cookie remains the same, and the server tries to use the later one). @tbeerman how does your deployment look like? What are the hostnames for your auth server, UI, etc.? Trying to understand why it didn't work for you in the first place, where the cookie was only set for the `webhome` domain.

**Comment by rizart** [comment]
This issue has been hanging for long now, I understand this will not be relevant with the new UI @maany @bari12  , should we just conclude/close this?

**Comment by bari12** [comment]
Sorry @rizart for just getting back to this now. It would still be good to understand what exactly goes on here. Maybe @tbeerman can help as well. Will still take a bit of time until we deprecate the old webui and go over to the new one.

**Comment by bari12** [comment]
I am closing this now, since this be solved with the new UI.
