### ISSUE TITLE
Do not require space tokens for SRM

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#574]
At many CMS sites, space tokens are not used even when SRM is utilized.  However, it's not currently possible to skip this setting.

It may be as simple as setting the space token to the empty string (``), which could be done automatically if not specified.

However, there might be hidden dependencies that want a non-empty-string space token.  Needs investigation.

**Comment by nataliaratnikova** [comment]
Currently Rucio unconditionally passes  spacetoken json parameter to FTS job.  No matter what value is passed, this causes fts error on CMS sites which do not support spacetokens.
The desired behavior is: if space_token is not in the 'extended_attributes' , do not add spacetoken to fts json.

**Comment by bbockelm** [comment]
Lines that need fixing:

* https://github.com/rucio/rucio/blob/master/lib/rucio/transfertool/fts3.py#L171
* https://github.com/rucio/rucio/blob/master/lib/rucio/daemons/conveyor/common.py#L165

**Comment by nataliaratnikova** [comment]
Hi @bbockelm ,   how do I now define an RSE so that it would not pass the spacetoken  to FTS? 
Adding 'srm' protocol still requires a non-empty spacetoken argument : 
`# rucio-admin  rse add-protocol --hostname 'stormfe1.pi.infn.it' --scheme 'srm' --prefix '/cms/store/test/rucio'  --web-service-path '/srm/managerv2?SFN='  --port '8444' --impl 'rucio.rse.protocols.gfalv2.Default' --domain-json '{"wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 1}}' --space-token ''  T2_IT_Pisa `
`Error: space-token and web-service-path must be provided for SRM endpoints.`
