### ISSUE TITLE
New endpoint for X509 certificate getPeerCert

### ISSUE THREAD

**Issue by nimishbongale** [rucio/rucio#5834]
Motivation
----------
Enabling the new workflow for x509 certificate acquisition in the new React-based WebUI will require us to make an explicit endpoint where the `getPeerCert()` method within the flask server can be invoked. This will cause a cert selection pop-up to come up on your browser, and the rest of the flow remains unchanged.

Modification
------------

Make an endpoint which invokes the `getPeerCert()` method.

**Comment by bari12** [comment]
@nimishbongale @maany who will implement this?

**Comment by maany** [comment]
We should provide this as an `optional` feature, which can be used in deployment scenarios where rucio can run independently of a server like Apache/Ingress controllers etc. For instance,  K8s Openstack Layer 7 Loadbalancer, where requesting client certificates is currently not possible, could leverage this optional feature.

**Comment by maany** [comment]
Adding more info for this issue: 
This is a webui-specific feature. Ideally, the UI and its deployment strategy should be enough to fetch an x509 from the User. However, since we could not use React to trigger a SSL/TLS Client Certificate Request,  this issue is related to creating a webui-specific endpoint that could initiate the SSL client certificate request on behalf of the new WebUI.
