### ISSUE TITLE
Bad replicas declaration silently fails with server on 1.29.2 and client <1.29.2

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#5867]
Motivation
----------
This commit modified the REST API for declaring bad replicas :  
https://github.com/rucio/rucio/commit/335bc1deb7623f363da95ca6709c9a8de83f2d21
It replaces the `pfns` parameter by `replicas`. The client API is properly modified, so if one uses `1.29.2` on the server and client everything is fine. But using a client prior `1.29.2` with a server on `1.29.2` will silently fail the declaration of bad files (which did happen to ATLAS). Would it be possible to still use `pfns` if `replicas` is not send ?

Modification
------------

**Comment by ivmfnal** [comment]
I am afraid I do not understand the issue.

The `api.declare_bad_file_replicas` code did already work with both before my change. I simply renamed the argument from “pfns” to “replica” because the code already was able to work with both, not only PFNs and the name "pfns" was misleading. I also found all the places in the server side code which uses this function and changed declare_bad_file_replicas(pfns=value,...) to declare_bad_file_replicas(value,…).
My understanding is that the code can not be used by the client because it is in `api` module.

Please explain the issue.
