### ISSUE TITLE
remove podman-specific settings in docker-compose*.yml

### ISSUE THREAD

**Issue by ThePhisch** [rucio/rucio#5983]
### Description

adding new images to the docker-compose files in /etc/docker/dev is very tedious, since the current setup makes heavy use of largely undocumented and likely unnecessary.

### Motivation

i am trying and failing to add a webdav server to the docker-composes. using a pure docker-compose approach, i have already managed to create a functioning docker-compose file. In addition, refactoring the current docker-compose yamls to a format that is more commonly used has the advantage of being easier to maintain and faster to understand for new developers.

This change would not necessarily break compatibility with podman. The issue lies with podman-compose.

### Change

refactor the etc/docker/dev/docker-compose*.yml files to use settings more natural to docker-compose (and which are well documented). Specifically, getting rid of `network_mode` and `external_hosts` would simplify the

**Comment by rcarpa** [comment]
Can you please be more detailed about what podman-specificities you encountered and why it's too costly to maintain the compatibility with both systems ?

**Comment by ThePhisch** [comment]
the current setup makes use of a parameter called `network_mode` in each container except for the rucio container. In the rucio container, he parameter `extra_hosts` is made use of. @maany and I came to the conclusion that these are used to ensure compatibility with podman. However, they are not well documented.
Difficulties came up when adding a webdav container for issue #5962. These issues did not exist in a plain docker-compose (i.e. without podman compatibility). The best way forward seems to be to drop podman.

**Comment by rcarpa** [comment]
I would, arguably, argue that the best way forward is to try to keep the compatibility if it's possible. It's definitely easy to pick the vendor locking path. But do we want it ?

**Comment by maany** [comment]
Dockerfile specification, while starting out as Docker-specific, has become a standard that is compatible with other container builds/runtimes engines like cri-o, containerd, etc. No issues there and the images are definitely not vendor-locked. The same images can be used in development, testing, prod with kubernetes, docker-compose, podman-compose etc..

We only use docker-compose for development and integration tests and I doubt there are any production use-cases unless you run it as services in swarm-mode. So, a vendor lock-in here would affect the developers using podman as the integration tests use docker-compose. 

The docker-compose specification is supposed to be "compatible" with podman-compose, so it would be nice to have the docker-compose files that can run with both. @ThePhisch could you test that your modified files can be built and run with podman and podman-compose? 

However, if most of the community just uses the docker-compose set-up for development, then the extra hassle of maintaining compatibility with podman-compose in a single file might not be worth the effort especially if these specifications start diverging at some point. We are already seeing undocumented fields ;) 

It might be better to have separate files ( one for docker-compose, other for podman-compose) that use the respective `compose` technology optimally

**Comment by rcarpa** [comment]
I still only see generic wording without specific: "functionality X doesn't work with podman, but works with docke. We need it very much, there is no alternative, so we break compatibility".

**Comment by maany** [comment]
To clear up some confusion, let's not mix `docker and podman` with `docker-compose and podman-compose` respectively.  We support docker and podman for building our images and running the containers individually.
To be more specific, I have verified that we can run the following commands with both docker and podman

```
docker/podman build -t <rucio-something> -f /path/to/rucio-something-Dockerfile
```

and these images can start the container using either podman or docker:

```
docker/podman run [Options] <rucio-something>
```

What we do not currently support is `podman-compose`. If you try to run any of the `docker-compose-*.yml` files (both existing ones and the one Anton is writing) with `podman-compose`, the command fails due to bugs in the implementation of the [compose specification](https://www.compose-spec.io/) by the [podman-compose project](https://github.com/containers/podman-compose)

```
$ podman-compose -f etc/docker/dev/docker-compose-storage.yml up
['podman', '--version', '']
using podman version: 1.6.4
** excluding:  set()
['podman', 'network', 'exists', 'dev_default']
Error: unrecognized command `podman network exists`
Try 'podman network --help' for more information.
['podman', 'network', 'create', '--label', 'io.podman.compose.project=dev', '--label', 'com.docker.compose.project=dev', 'dev_default']
Error: unknown flag: --label
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 563, in assert_cnt_nets
    try: compose.podman.output([], "network", ["exists", net_name])
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 820, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['podman', 'network', 'exists', 'dev_default']' returned non-zero exit status 125.
```

So, one of the questions is not about supporting `Docker` or `Podman`, but more about supporting `Docker-Compose` and `Podman-Compose`.  Podman Compose is buggy, not well maintained and does not evolve with podman. We should NOT use it.

If we all agree on this. Then let's continue on the follow-up issue with how the `docker-compose` files are written. More specifically, the implications of using `network_mode: "service:rucio"` that I will write in a follow-up comment here

**Comment by rcarpa** [comment]
I'll take care of this ticket

**Comment by maany** [comment]
Sure, I will comment on what I find on this issue here. I would prefer to discuss things and come to some sort of an agreement on what the docker-compose files should look like and why, before implementing the solution

The issue description is indeed misleading @ThePhisch. Could you make it more specific instead about docker-compose/podman-compose? Whatever we end up doing, it is NOT going to have any impact on docker/podman support.

**Comment by ThePhisch** [comment]
I specified the issue description, making use of the insights gathered up to now. Most importantly, the new issue description acknowledges that the problem seems to lie in the implementation of docker/podman-compose and not docker/podman itself.
