### ISSUE TITLE
Problem with multihop transfer between 2 cloud RSEs

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#6036]
### Description

Transfers between 2 clouds endpoints is currently not supported and need to be hopped though an intermediate RSE. In this example : https://fts3-pilot.cern.ch:8449/fts3/ftsmon/#/job/b568e444-8db4-11ed-8b35-fa163ec6a1a1 the hop doesn't respect the `verify_checksum: False` for the initial RSE

### Steps to reproduce

...

**Comment by rcarpa** [comment]
Is this just a problem with checksums or something else ? The logic of verify_checksums: false is probably broken because the string is never parsed into a boolean : https://github.com/rucio/rucio/blob/f7dd62f7619715bb487d8f26b7b213f7e8d3979a/lib/rucio/transfertool/fts3.py#L126

**Comment by rcarpa** [comment]
This is a particularity with multihop transfers on FTS side. "verify_checksum" is a job_parameter. Meaning it should be set for the entire job. In a multi-hop transfer, the meaning of this parameter is not clearly defined. Lets assume a transfer job

RSE1(verify_checksum=False) -> RSE2(verify_checksum=True) -> RSE1(verify_checksum=True)

There is no way to correctly define that the checksum must be checked only on destination for first hop; but on both source and destination for the second one. Setting it to "destination" will result in only destination to be checked both on first hop and second hop. 

Rucio builds these job parameters only from the last hop right now: 
(https://github.com/rucio/rucio/blob/f7dd62f7619715bb487d8f26b7b213f7e8d3979a/lib/rucio/transfertool/fts3.py#L261) 
This convention is here since forever.  

I strongly believe it's a wrong convention for verify_checksum. Something more intelligent has to be done. But we'll have to use the most relaxed verify_checksum possible. Meaning: if a hop doesn't support the verification of the checksum, it will be completely disabled for the entire job and never checked. This even if other hops support it. @bari12, any opinions about this solution ?

**Comment by bari12** [comment]
I agree, this entire `verify_checksum` business was done without having multihops in mind at all. Some smarter solution would be best.
