### ISSUE TITLE
Protocol Priority Renumbering

### ISSUE THREAD

**Issue by bjwhite-fnal** [rucio/rucio#6083]
### Description

Please add a configuration option to either enable or disable (depending on the default) automatic renumbering of protocol priorities when gaps emerge.

### Motivation

This causes substantial trouble for DUNE, who have a large number of RSEs that are in a state of configuration flux as the experiment evolves. Protocols at this time are frequently added and removed from the multitude of RSEs as sites develop their storage capabilities.  Returning to the original default behavior where priorities are not changed server-side when gaps emerge would greatly simplify administration of individual RSE protocols by returning to my original suggestion to experimenters to "delete the protocol in question and recreate it".

### Change

My opinion is that the default should be the old behavior, where no action is taken by Rucio to fill gaps in the protocol priorities for an individual storage endpoint. A configuration option could be used to enable this for communities that require automatic balancing.

**Comment by bari12** [comment]
I am trying to investigate this a bit, but all the code which fills/re-orders the gap is 10/11 years old. E.g. the update_protocol, delete_protocol code. Are you sure the behaviour you describe as "old" existed?
@dchristidis do you remember this?

I think we can add something, but I would rather keep the behaviour as it is, and add the skip-fill-gaps as an option.

**Comment by dchristidis** [comment]
No, I’m afraid I can’t remember this being the case. However, we rely on CRIC for the protocol configuration, so if anything changed in the underlying behaviour, it is unlikely that we would notice.

**Comment by bari12** [comment]
I was specifically looking at things like this
https://github.com/rucio/rucio/blob/e852b1697ed2e59fb0355127c290241051ac1694/lib/rucio/core/rse.py#L1326-L1363
or
https://github.com/rucio/rucio/blob/e852b1697ed2e59fb0355127c290241051ac1694/lib/rucio/core/rse.py#L1414-L1426

But all these snippets are 6-10 years old.

**Comment by bjwhite-fnal** [comment]
We definitely didn't seem to see this before upgrading to 1.29. It may be old, but was untriggered for some reason possibly?

We can certainly live with an "off switch" configuration option if that's what you prefer.

**Comment by bari12** [comment]
It's possible that this was just never triggered yes. In any way, I would prefer to keep this as the standard now, since it was the original intention. Let's add the option to turn it off instead.

**Comment by dchristidis** [comment]
Wouldn’t it be more appropriate to push protocols down when adding them instead?

To elaborate, I was suggesting refactoring this code into a function that would reorder protocols as appropriate, no matter what the operation. Though more difficult to get right, I think it makes sense because 1) it adds symmetry, 2) it avoids problems where you add new protocols with priority 1, so now you have more than one protocol with the same priority and have lack of determinism as to which one will be used, and 3) I have the impression that it will still solve DUNE’s issue (though Brandon should correct me).

**Comment by bjwhite-fnal** [comment]
My first thought is say you have 4 protocols with priorities [1,2,3,4]. What would be the proper course of action if you were to add another protocol with priority 3? Should it always push 3 to 4, and 4 to 5?


What happens if you want to modify the protocol with priority 2 to instead be priority 4?
@dougbenjamin may have thoughts.

**Comment by bari12** [comment]
@dchristidis and I discussed this a bit, I am considering if we should just remove the re-ordering/gap filling entirely, just like Brandon suggested. We would have to at least adapt the current algorithm, since it would make the changes done in #697 basically useless. You can add protocols with the same priority (Which is a valid usecase) but when you update/delete a protocol on that RSE, they would get re-ordered. But mostly I am thinking, I am not sure if we need to care that there are gaps in between the protocols, as long as an order can be established.

I will bring this up in the dev meeting tomorrow.

**Comment by StevenCTimm** [comment]
The reason we ran into this with dune is that we were trying to make this scheme.

  https
    domains: '{"lan": {"read": 2, "write": 1, "delete": 1}, "wan": {"read": 2, "write": 1, "delete": 1, "third_party_copy_read": 1, "third_party_copy_write": 1}}'
  root
    domains: '{"lan": {"read": 1, "write": 2, "delete": 2}, "wan": {"read": 1, "write": 2, "delete": 2, "third_party_copy_read": 2, "third_party_copy_write": 2}}'

we have https preferred for write and root preferred for lan/wan read.. There would be no way to actually create
this scheme from scratch with the current behavior of the software.

Ideally we would like to be able to modify priorities without deleting/recreating the protocol.  That was always a hassle.
But if we do delete and create the protocol we need to be able to keep the other ones holding their place.

**Comment by bari12** [comment]
We discussed this in the dev meeting recently and decided to take the automatic re-ordering out completely. Possibly add an option where you can trigger a sort manually.

**Comment by StevenCTimm** [comment]
What about the capacity to tweak priorities of a protocol without deleting it will that ever happen?
________________________________

**Comment by dchristidis** [comment]
This is already possible through all the layers except the CLI.

**Comment by StevenCTimm** [comment]
OK thanks for the explanation and thanks for taking the automatic re-ordering out, it will be a big help for us.

Steve Timm

________________________________
