### ISSUE TITLE
Authentication: Make Rucio a SciTokens issuer

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#609]
Motivation
----------
The SciTokens project aims to build a federated ecosystem for authorization on distributed scientific computing infrastructures. Rucio should be made a full-fledged SciTokens issuer to make it easy to integrate with SciTokens-enabled storage and SciTokens-enabled transfer systems. Since Rucio already supports token-based authentication, issuing SciTokens would not be too difficult. 

Expected behavior
-----------------
Clients should be able to ask Rucio for a SciToken next to the X-Rucio-Auth-Token.

**Comment by mlassnig** [comment]
More info: http://scitokens.org/

**Comment by vingar** [comment]
@bbockelm Won't the workflow be similar with openId ?

Something like:
Client,          rucio auth servers,      ext auth. service (openId/scytoken)
ask token --------> forward token request -----> token request
store token <----  store token in db and answer with it to the clients   <---- give token

then interacts with Rucio & co

**Comment by mlassnig** [comment]
Not quite, because the Rucio server itself will be the issuer. If Rucio allows you to get an X-Rucio-Auth-Token you can request a SciToken instead (with the appropriate domains set based on VO policy).

**Comment by vingar** [comment]
in X-Rucio-Auth-Token you expect to have the SciToken one ?

**Comment by mlassnig** [comment]
The client can request it in addition and use it to go to storage (If the storage allows the domain).

We can also think to use it as a replacement for X-Rucio-Auth-Token with a custom Rucio-Auth domain.

**Comment by bbockelm** [comment]
I'd suggest starting out by having them alongside each other (to understand how the library works), then eventually replacing `X-Rucio-Auth-Token`.

**Comment by vingar** [comment]
The clients will have to store both tokens and put in addition the sciToken one in the request header `Authorization: Bearer <token>` for the next interactions (rucio, storage, etc).  Am I correct ?

**Comment by bbockelm** [comment]
Yeah - at the beginning, one would just use the SciToken for interaction with storage.

In fact, this is a strong argument for keeping multiple tokens -- you don't want the storage authorization token to additionally interact with Rucio.

So, your Rucio token would gain a new format (which is convenient because it doesn't have to be serialized by Rucio) and you'd still separately handle a storage-related token.

While Rucio and the storage service would need to understand how to verify / parse the token, the client can continue to treat it as an opaque string.

**Comment by mlassnig** [comment]
Superseded by https://github.com/rucio/rucio/issues?q=is%3Aissue+OAuth2%2FOIDC+is%3Aclosed
