### ISSUE TITLE
Incorporate IAM-based testing for token workflows

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#6188]
### Description

The upcoming development for token-based workflows requires the ability to run an identity provider in our development and testing environment. As a first goal, we need to investigate how well we can integrate IAM in them (ideally at the same level as FTS).

**Comment by esilvaju** [comment]
Talking with @vokac, he recommended to talk with CERN IAM team about this topic, since they should have ATLAS test IAM instance. He raise with them via e-mail and we continue from there (I'm in CC).

**Comment by vokac** [comment]
We discussed that it'll be easier to use existing token issuer for Rucio token development testbed, because it'll make storage configuration easier / identical to the configuration that we need anyway for ATLAS / WLCG tokens. First we considered ATLAS IAM instance with special scope policies defined for Rucio testbed IAM client allowed to get `storage.*:/atlastestdisk/` scopes in the token, but for practical reasons it'll be easier to use similarly configured WLCG IAM. I'll ask one storage provider for each SE implementation (EOS, dCache, StoRM, XRootD) to configure access for WLCG tokens.

**Comment by bari12** [comment]
This isn't really possible, nor a good idea to do. We need this containerised for our own isolated development environments plus for the CI environment on GH. I do not want to connect any of these to an actual instance. This will be a pain to do, requires to have actual credentials used in GH etc. This also must be independent of ATLAS, since we need to be able to run this for other (possibly non-WLCG) communities.

That being said, of course we will need to run tests like @vokac suggested, but this will not come from the CI, nor from the dev environment mentioned here.

**Comment by esilvaju** [comment]
I created a [repository](https://github.com/esilvaju/Rucio-IAM) with docker-compose file and instructions that makes possible to spin up an IDp.

The next step is to integrate this containers to the Rucio test environment.
