### ISSUE TITLE
Plugin module for Auto Approval

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/rucio#6203]
### Description

At the moment rules eligible for auto approval need to satisfy the following conditions like `len(rses) == 1`, `len(bytes)<'value_set_in_rse_attribute'>`. 

However, we would like to make it configurable, allowing us to automate certain approvals in our workflow that cannot be defined using `number_of_files` and `bytes`. 

### Motivation

We are experimenting with an option to allow rule creation to users that follow certain criteria, like pre-defined `rse_expressions` and their `global usage`, to users, without messing with their current local quota allocations.  

### Change

If we all find it suitable. We envision a module of the likes of permissions. 
https://github.com/rucio/rucio/blob/ea4d2c7e2702b85a86a8668b2d852971f42fceb4/lib/rucio/core/rule.py#L255

This will be followed by the plugin invocation. 

FYI @drkovalskyi @dciangot

**Comment by bari12** [comment]
Hi Rahul,

I think this makes a lot of sense. We should maybe think though of a good "boiler-plate" way to have these plugin-hooks imported from the policy, and executed throughout the code. For the permission/policy this is quite clear, because everything comes from `rucio.core.permission.has_persmission`, but we should do it for other things as well.

For the lfn2pfn algorithm we have 
https://github.com/rucio/rucio/blob/215524297f3d13369edda948d2622bb3e1412097/lib/rucio/common/utils.py#L1757
Which we might want to use for this as well.

Maybe @jamesp-epcc wants to comment here too. We should also document this way of adding policy hooks then better.

**Comment by jamesp-epcc** [comment]
I'm not very familiar with the rules part of the code, so I'm not sure exactly how it should be integrated, but I would recommend creating a new class of algorithm that can be registered from policy packages, similar to the lfn2pfn, SURL and scope extraction classes that already exist. I will add some documentation on how to do this.
