### ISSUE TITLE
Outdated documentation on implementing metadata plugins

### ISSUE THREAD

**Issue by maxnoe** [rucio/rucio#6601]
### Description

The documentation mentions a DIDMetadataPlugin, but the link in that class just links to the homepage of the documentation and this class doesn't seem to be defined in the current repository. 

https://rucio.github.io/documentation/operator/did_meta/#how-to-develop-a-custom-metadata-solution

### Steps to reproduce

Go to the above documentation link

### Rucio Version

Current release

**Comment by rdimaio** [comment]
The DidMetaPlugin exists: https://github.com/rucio/rucio/blob/master/lib/rucio/core/did_meta_plugins/did_meta_plugin_interface.py, but the documentation had a wrong link that linked to the homepage instead of the plugin code. @voetberg opened a PR to fix this: https://github.com/rucio/documentation/pull/302

For future issues relating to the documentation, please open them in the documentation repository: https://github.com/rucio/documentation

**Comment by maxnoe** [comment]
@rdimaio thanks! For some reason I searched for `DIDMetadataPlugin` not `DIDMetaPlugin`
