### ISSUE TITLE
blake3 algorithm for data integrity

### ISSUE THREAD

**Issue by Germano0** [rucio/rucio#6829]
### Description

Good day, former CMS VOC here. **The following statements are my personal thoughts.**
I recently started using (for personal use) [blake3](https://github.com/BLAKE3-team/BLAKE3) [1] cryptographic hashing algorithm to double check the integrity of some OpenZFS datasets and I appreciated its outstanding performances over the sha256 I was using previously.
So my mind went to my ex colleagues of the CMS data transfer team,  wondering what data integrity algorithm they were using, so I asked around and I heard that Rucio uses MD5 and Adler32.
Therefore I am filling this ticket cause I think blake3 can be very useful in saving many computational resources during data validation.
Hereby I attach a short benchmark between blake3 and md5 for data validation of a Fedora ISO image, where blake3 was ~10x faster than md5. The computer is a Thinkpad X13 Gen 3 with AMD Ryzen 7 PRO 6850U 
```
user@X13:~/ISO_Linux$ hyperfine --warmup 3 --shell=none 'md5sum Fedora-KDE-Live-x86_64-40-1.14.iso'
Benchmark 1: md5sum Fedora-KDE-Live-x86_64-40-1.14.iso
  Time (mean ± σ):      3.530 s ±  0.094 s    [User: 3.134 s, System: 0.372 s]
  Range (min … max):    3.405 s …  3.711 s    10 runs
 
user@X13:~/ISO_Linux$ hyperfine --warmup 3 --shell=none 'b3sum Fedora-KDE-Live-x86_64-40-1.14.iso'
Benchmark 1: b3sum Fedora-KDE-Live-x86_64-40-1.14.iso
  Time (mean ± σ):     373.0 ms ±  21.5 ms    [User: 2174.4 ms, System: 596.3 ms]
  Range (min … max):   356.4 ms … 418.2 ms    10 runs
```

Best regards

[1]: via `b3sum` utility

**Comment by bari12** [comment]
The choice of checksum algorithm is not really Rucios choice. We could use easily use another one, but the driving factor here is what the storage systems support, and right now this is predominantly adler32 and md5.

After a third-party-copy transfer, or an upload, the destination or source storage system is asked what the checksum is it calculated of the receiving file. This is then compared with the checksum Rucio calculated, and has in its catalog. But unless the storage system cann reply a checksum, such as blake3, it is pointless if Rucio calculates it, since there is none it can compare it to. 

So a move to a different checksum algorithm, while much appreciated by many, would require a shift in the entire ecosystem, which is much harder to implement.
