### ISSUE TITLE
Work on the demo

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#696]
Motivation
----------
Demo is empty

Modification
------------
Create RSEs, DIDs...

**Comment by mlassnig** [comment]
@cserf  Here's my feedback for the demo, all done on Debian:

- https://github.com/rucio/rucio/tree/master/etc/docker/demo needs to have at the beginning a link that one needs to git clone the repo ;-)

- dockerd was not running for my automatically, had to start manually

- compose ended with:

ERROR: for rucio  Cannot start service rucio: driver failed programming external connectivity on endpoint demo_rucio_1 (15c536c53720fcdcf7513b73d3764723223849ba4b56b50fe29c5ee7139234b4): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

changing it to 8443 made it work

(which was weird anyway, because i have nothing running on 443)

- other than that it worked

**Comment by vingar** [comment]
The part describing the installation is nice ( a really good work guys!).

I've extended and rst-formated the README in #772 plus adding it in the main index of the documentation with a new Tutorial/demo section.

For me, the remaining part is to extend `doc/source/rucio_demo.rst` with more examples from rucio-ping, to how to configure rucio, rse, accounts etc, and then how to use rucio: find files, upload, download, etc.  Merge and integrate some examples from cli_admin_examples.rst and cli_examples.rst
