### ISSUE TITLE
extracting (scope,name) in bad-replica declaration doesn't work anymore on certain cases

### ISSUE THREAD

**Issue by faluchet** [rucio/rucio#7044]
### Description

There has been a breaking change since https://github.com/rucio/rucio/commit/cf9c2c7afad37fc5b7bdd782e281918b4230b2f1 .

On the ATLAS instance, 'get_scope_protocol()' in https://github.com/rucio/rucio/blob/master/lib/rucio/core/replica.py#L297  returns the _default algorithm instead of the _atlas one. I have not clear yet if it has to do with some missing policy configuration or something else and it needs more digging.

### Steps to reproduce

```
$ rucio-admin --verbose replicas declare-bad --reason 'some reason' root://example.com:1111//prefix/user/faluchet/ab/cd/user.faluchet.example
PFNs that will be declared bad:
root://example.com:1111//prefix/rucio/user/faluchet/ab/cd/user.faluchet.example

SOME_RSE : PFN (user, 'user.faluchet.example') Unknown replica cannot be declared.
Completed in 0.0638 sec.
```

Trivially, if I try to reproduce it manually by passing the intended vo explicitly, one can notice the differences:
```
>>> from rucio.rse import rsemanager as rsemgr
>>> my_parsed_pfn="{'scheme': 'root', 'port': '1111', 'hostname': 'example.com', 'path': '/user/faluchet/ab/cd/', 'name': 'user.faluchet.example', 'prefix': '//prefix/', 'web_service_path': ''}"

>>> scope_proto = rsemgr.get_scope_protocol(vo='def')
>>> scope_proto(my_parsed_pfn)
('user.faluchet.example', 'user')

>>> scope_proto = rsemgr.get_scope_protocol(vo='atlas')
>>> scope_proto(my_parsed_pfn)
('user.faluchet.example', 'user.faluchet')
```

**Comment by voetberg** [comment]
It may have to do with the policy configuration yes - do you have that section on hand? If config[policy][pfn2lfn] isn't 'atlas', that would case the above behavior

**Comment by rdimaio** [comment]
> It may have to do with the policy configuration yes - do you have that section on hand? If config[policy][pfn2lfn] isn't 'atlas', that would case the above behavior

Yeah, we don't have `pfn2lfn` set in the ATLAS cfg file, so it defaults to the default algorithm. Closing this issue and opening one in the ATLAS repo

**Comment by rdimaio** [comment]
Re-opening this issue as I had wrongly closed it.

This is related to this issue: https://github.com/rucio/rucio/issues/7049

This PR should fix both issues: https://github.com/rucio/rucio/pull/7053

**Comment by rdimaio** [comment]
for ATLAS: explicitly mentioning `pfn2lfn = atlas` in the `policy` section of the config seems to fix the issue, but if nothing is specified in the config, the issues persist - this is unexpected, since it should default to the VO, and thus use the `atlas` algorithm anyway.

Re-opening this issue to try to fix this problem, as it seems to be somewhere in the logic of how we register/choose which algorithm to use.

This functionality is currently untested (AFAIK) in our test suite, so I'll write some tests to try and identify the issue.

**Comment by jamesp-epcc** [comment]
I don't know exactly how the ATLAS Rucio is deployed, but is the VO actually set to `atlas`? (in the `[client]` section of the config file). My understanding was that single VO installations would normally have the VO set to `def`, which in this case would result in the default algorithm being called instead of the `atlas` one.
