### ISSUE TITLE
RSEDeterministicScopeTranslation algorithm registration results in parsing error

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#7049]
### Description

The order of the algorithms defined for the `RSEDeterministicScopeTranslation` are in the wrong order.

https://github.com/rucio/rucio/blob/bd5196af7202bd724831149848228e602d8f3f13/lib/rucio/rse/protocols/protocol.py#L49-L50

It should be `method, name`

### Steps to reproduce

1. Add `atlas` pfn2lfn policy
2. list_replicas
3. crash

### Rucio Version

35.2.1

**Comment by rdimaio** [comment]
The parameters are not in the wrong order,  `RSEDeterministicScopeTranslation.register` expects the parameters in the `name, method` order. The issue is in the constructor setting a different value for `algo_type` depending on whether a function is parsed from the policy package or not:

https://github.com/rucio/rucio/blob/bd5196af7202bd724831149848228e602d8f3f13/lib/rucio/rse/protocols/protocol.py#L53-L64

resulting in an inconsistency with the `register` method that always uses `cls.__name__` for registration:

https://github.com/rucio/rucio/blob/bd5196af7202bd724831149848228e602d8f3f13/lib/rucio/rse/protocols/protocol.py#L72-L74


which causes `get_parser` to fail with a `KeyError: 'pfn2lfn'` when the algorithm is parsed from the policy package:

https://github.com/rucio/rucio/blob/bd5196af7202bd724831149848228e602d8f3f13/lib/rucio/rse/protocols/protocol.py#L68-L70

**Comment by rdimaio** [comment]
I believe this is a regression from https://github.com/rucio/rucio/pull/6924/files
